### ISSUE TITLE
SDK 2.8.2 App get crashing

### ISSUE THREAD

**Issue by Adhamsheriff** [AgoraIO/Basic-Video-Call#100]
Hi,

After updating the latest SDK 2.8.2 App get crashing.

cannot initialize Agora Rtc Engine, error=101

     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int io.agora.rtc.RtcEngine.setVideoEncoderConfiguration(io.agora.rtc.video.VideoEncoderConfiguration)' on a null object reference

If using 2.3.0 ist working fine.

**Comment by plutoless** [comment]
@Adhamsheriff 101 usually means sdk is not properly initialized. please double check how you create rtcEngine instance

**Comment by Adhamsheriff** [comment]
@plutoless I just clone latest version code and added my App ID.
I didn't change any code.

**Comment by plutoless** [comment]
maybe you can set a debug breakpoint to take a look at variable?

**Comment by Adhamsheriff** [comment]
Okay @plutoless 
Let me check it.
