### ISSUE TITLE
Check  which camera is active, Front/ Rear

### ISSUE THREAD

**Issue by varunrathi28** [AgoraIO/Basic-Video-Call#101]
We have a requirement, where we would allow user to start video call directly from Front/Rear camera with feature to switch Camera. Currently, RTC switches the camera but we couldnt find a way to check which camera is currently active on RTC stream

**Comment by varunrathi28** [comment]
we are using RTC framework on iOS

**Comment by plutoless** [comment]
@varunrathi28  by default it's always front dealing with a newly created rtc engine instance

**Comment by varunrathi28** [comment]
@plutoless  Yeah. We were able to manage by keeping a bool and toggling it on every switch. It would have been better if were was a way to directly identify from the AgoraRTC instance if which camera was currently active.
