### ISSUE TITLE
Handle Cancelled call scenario.

### ISSUE THREAD

**Issue by varunrathi28** [AgoraIO/Basic-Video-Call#102]
We are using PushKit for sending notifcations on iOS. When we call a user :- 
1. The sender immediately logs in Signalling kit and Joins channel on RTC.
2. The receiver gets a pushkit notification, it shows a CallKIT UI and also logs in to the Agora signalling.
3. The receiver on accepting joins channel and updates the UI.

But if the sender cancels the call before the receiver can accept, and then receiver picks the call, there is a black screen. 

Is there is a way to identify if used has cancelled the call?

We tried the delegate callback for RTC :  didOfflineOfUid, but there is no callback.

**Comment by plutoless** [comment]
try using our rtm sdk. it has a more complete and better designed api for this
