### ISSUE TITLE
Agora-Web-Tutorial-1to1-React DEMO ERROR

### ISSUE THREAD

**Issue by fanpaa** [AgoraIO/Basic-Video-Call#103]
When I click the "JOIN" button, the following error will occur

![image](https://user-images.githubusercontent.com/2202938/67369806-40b08100-f5ac-11e9-8455-3aca65369287.png)
![image](https://user-images.githubusercontent.com/2202938/67369848-5160f700-f5ac-11e9-8eaf-57740dd9d1ed.png)

**Comment by mayank-shaan** [comment]
+1

**Comment by mayank-shaan** [comment]
@fanpaa Did you find any solution?

**Comment by plutoless** [comment]
https://github.com/AgoraIO/Basic-Video-Call/commit/63d2489d9468a0bc2a747b211cf9e6c36c85158f
