### ISSUE TITLE
Can't find Agora Video SDK for Linux

### ISSUE THREAD

**Issue by KCFeng** [AgoraIO/Basic-Video-Call#104]
In OpenVideoCall-Linux, it mentioned to download Linux SDK from Agora SDK website.
Unzip SDK and copy "libagora_rtc_sdk.so" to OpenVideoCall/libs folder.

But I can't find the Linux SDK zip from Agora SDK website.
> https://docs.agora.io/en/Agora%20Platform/downloads

There are only Android/iOS/Mac/Windows/Web/Electron.
Does Agora voice/video call still support Linux?

**Comment by plutoless** [comment]
sorry we don't have public release that supports linux yet.

**Comment by grzegorzk** [comment]
Hi @plutoless, I was looking around and can see no download for linux, any chance you have linux in your plans?
