### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'stream.stop')

### ISSUE THREAD

**Issue by eugenegodun** [AgoraIO/Basic-Video-Call#107]
Got this error in **Agora-Web-Tutorial-1to1-React**
![image](https://user-images.githubusercontent.com/26645888/68941931-dd330100-07af-11ea-8148-107de54c9255.png)
It looks like local stream is null

**Comment by plutoless** [comment]
im fixing it. will push a fix soon

**Comment by plutoless** [comment]
https://github.com/AgoraIO/Basic-Video-Call/commit/63d2489d9468a0bc2a747b211cf9e6c36c85158f
