### ISSUE TITLE
Where is mGridVideoViewContainer notified when new user joins group video call?

### ISSUE THREAD

**Issue by AxesandGrinds** [AgoraIO/Basic-Video-Call#108]
Hi,

In https://github.com/AgoraIO/Basic-Video-Call/blob/master/Group-Video/OpenVideoCall-Android/app/src/main/java/io/agora/openvcall/ui/CallActivity.java
I understand that mGridVideoViewContainer contains the recyclerviews of surfaceview of new user's video on video call. I have read through the file and cannot find where mGridVideoViewContainer is being updated when new user joins the video call. I can clearly see that when mUidsList.put(uid, local) is called inside the function "onJoinChannelSuccess" but mGridVideoViewContainer is not updated.

Can you please tell me where mGridVideoViewContainer is updated when user joins group video chat?

Thank you.

Sincerely,
Victor

**Comment by plutoless** [comment]
https://github.com/AgoraIO/Basic-Video-Call/blob/464ea459ab01499cb6841cccfc75389ae109cddc/Group-Video/OpenVideoCall-Android/app/src/main/java/io/agora/openvcall/ui/CallActivity.java#L661
