### ISSUE TITLE
Error in Open IOS Call

### ISSUE THREAD

**Issue by Darrow8** [AgoraIO/Basic-Video-Call#113]
In IOS, after going through all of the steps, I get this error:

Showing Recent Issues
No profile for team '48TB6ZZL5S' matching 'AgoraIODev2019' found: Xcode couldn't find any provisioning profiles matching '48TB6ZZL5S/AgoraIODev2019'. Install the profile (by dragging and dropping it onto Xcode's dock item) or select a different one in the Signing & Capabilities tab of the target editor.

I am using an Iphone 6 with the latest version of IOS

**Comment by plutoless** [comment]
please go to build settings, search for profile and change our profile to apple development/ios development

**Comment by Darrow8** [comment]
Great, thanks
