### ISSUE TITLE
Group Video / OpenVideoCall-macOS: remote video not shown when transitioning from 3 to 4 participants 

### ISSUE THREAD

**Issue by pfuternik** [AgoraIO/Basic-Video-Call#114]
With 3 total participants (self + 2 remote), the layout of the tiles is displayed correctly.

When adding a 4th participant (self + 3 remote), the newly joined participant does not get displayed.

When adding a 5th participant (self + 4 remote), a third row is displayed and now ALL participants are displayed correctly.

When removing the 5th participant, 4 total participants are displayed correctly.

So the bug occurs when going from 3 to 4 total participants.

**Comment by pfuternik** [comment]
See images:
3tiles: 4 participants are in the channel but only 3 displayed
5tiles: 5 participants are in the channel and all 5 are displayed

<img width="964" alt="3tiles" src="https://user-images.githubusercontent.com/24925258/70100398-95a9d300-15ff-11ea-9cca-8a9374a8d7f3.png">
<img width="967" alt="5tiles" src="https://user-images.githubusercontent.com/24925258/70100399-95a9d300-15ff-11ea-9a11-8c0039113bcf.png">

**Comment by CavanSu** [comment]
fixed this issue on branch dev/3.0.0

**Comment by CavanSu** [comment]
We wiil fix this issue on Version 3.0 of Agora RTC SDK. There is a workaround, you can add a key-value on info.plist.

<img width="696" alt="WechatIMG1111" src="https://user-images.githubusercontent.com/22071286/70112472-6ee7ad00-1690-11ea-9d0c-b0f28820810d.png">

**Comment by pfuternik** [comment]
Thank you! Can you please point me to the commit in the dev/3.0.0 branch that fixed the layout bug?
