### ISSUE TITLE
cannot open source file

### ISSUE THREAD

**Issue by qiuyanli1990** [AgoraIO/Basic-Video-Call#117]
when build the sample code, it always report 
Error	1	error C1083: Cannot open include file: 'IAgoraRtcEngine.h': No such file or directory	c:\openvideocall-windows\openvideocall\stdafx.h	

![image](https://user-images.githubusercontent.com/58502052/70310570-ec571d00-184a-11ea-9716-95a0588ce7e0.png)

tried both VS 2019 & 2013.  
include additional path is checked

**Comment by sbd021** [comment]
You need dowload agora sdk, then unzip the file.   Copy sdk folder to the path where OpenVideoCall.sln is located in.
