### ISSUE TITLE
iOS Group Video Call : Unable to find uid of remote stream when create channel using joinChannelByUserAccount method

### ISSUE THREAD

**Issue by NirajCapermint** [AgoraIO/Basic-Video-Call#125]
I have created a channel using 
```
`- (int)joinChannelByUserAccount:(NSString * _Nonnull)userAccount
                          token:(NSString * _Nullable)token
                      channelId:(NSString * _Nonnull)channelId
                    joinSuccess:(void(^ _Nullable)(NSString * _Nonnull channel, NSUInteger uid, NSInteger elapsed))joinSuccessBlock;` 

``` 

But when someone joined the same channel using account, then how can we find which user joined the channel by using account?

All delegate methods in documentation for remote stream requires passing uid, but since I am using account instead of uid, I am not able to match which user joined / left channel. Is there a way in which I can find which user joined/left the channel using account instead of uid ?

**Comment by plutoless** [comment]
please listen to this callback
https://docs.agora.io/en/Interactive%20Broadcast/API%20Reference/oc/Protocols/AgoraRtcEngineDelegate.html#//api/name/rtcEngine:didUpdatedUserInfo:withUid:
to get mapping of account <-> uid

**Comment by NirajCapermint** [comment]
Thanks @plutoless, this one did the trick for me
