### ISSUE TITLE
Multiple broadcast.

### ISSUE THREAD

**Issue by kaushikbhut** [AgoraIO/Basic-Video-Call#128]
Hi @plutoless,

![IMG_0230](https://user-images.githubusercontent.com/52907987/72509172-fcf8ab00-386c-11ea-87d1-1a9cecfac600.PNG)

I want this type of view with multiple broadcasters. 
My requirement is showing all current broadcast(Live) in the bottom horizontal list and selected one will be displayed as the main view as same as the attached image.

Thanks.

**Comment by plutoless** [comment]
you can simply create a scrollview and put renderers in it, then use setRemoteCanvas when broadcaster joins

**Comment by plutoless** [comment]
remember you may want to muteRemoteVideoStream when someones video is scrolled out of visible area

**Comment by kaushikbhut** [comment]
Thanks for your replay.
If you don't mind can you provide any sample code or related code or any similar link for the same?
