### ISSUE TITLE
Carthage support for framework files

### ISSUE THREAD

**Issue by varunrathi28** [AgoraIO/Basic-Video-Call#129]
Hi,
We have been using Agora for a while. We noticed that there is no Carthage support for the framework files. Is it possible to add Carthage support for the RTC and signalling SDK?

**Comment by plutoless** [comment]
is CocoaPod not an option for you?

**Comment by varunrathi28** [comment]
Currently we are in the process of migration to Carthage from pods. In the current scope, Pod can work, but Carthage is the ideal solution for us in the long run. However, i couldn't locate Cocoa Pod support as well for the SDK.

**Comment by varunrathi28** [comment]
I tried to integrate AgoraSigSdk framework (with the .framework files available on Agora.io website) with binary specification on our repo with Carthage. Carthage fetches and downloads the AgoraSigSdk.framework file but is unable to read it. 

> I observed that there is no info.plist file in the framework. So i was curious if it is a Static framework?

However, we are using **Carthage 0.30.1 which supports Static frameworks.**

**Comment by plutoless** [comment]
so does that mean if we include info.plist in our sdk, you will be able to use carthage to integrate it？

**Comment by varunrathi28** [comment]
We can try... Since its framework, so carthage would need to version it.
Without Info.plist, it would fail to fetch version.

**Comment by plutoless** [comment]
maybe you can try providing a fake one yourself first? or you may make an open source one to help other developers who may need similar help

**Comment by varunrathi28** [comment]
I am not sure if it would work without authentic bundle identifier

**Comment by plutoless** [comment]
usually a library (which carthage and cocoapod help to integrate) should not need a bundle identifier
