### ISSUE TITLE
OpenVideoCall-Android - No code documentation

### ISSUE THREAD

**Issue by smithaaron** [AgoraIO/Basic-Video-Call#130]
Apart from a very small handful of inline comments, the sample app's code is not documented at all. At the very least I would expect document comments on classes and public methods explaining their purpose. There are quite a number of custom layouts and views, and it's not immediately clear if or why they're required.

**Comment by plutoless** [comment]
maybe you can point out some of them so that i can explain? the purpose of the demo is to help you understand how to use our sdk so maybe we focus more on sdk relevant functions.

**Comment by smithaaron** [comment]
> the purpose of the demo is to help you understand how to use our sdk

Exactly. However I count 36 classes in the sample. The purpose of a handful, such as the Activities, are obvious, but to understand the rest requires digging into a lot of code and trying to separate the essential sdk functionality from the specific implementation details for this app. This is made much more difficult due to the lack of commenting. Just a few lines at the start of each class explaining its purpose would make the task a lot easier. 

Neglecting comments and documentation on a personal project would be understandable, but on a project whose sole purpose is to help developers understand how to use the SDK, it's inexcusable IMO.

**Comment by plutoless** [comment]
developers have different perspectives reading code, if you can give me some concrete suggestions, e.g. the places where you believe should have some comments, and what comments would be, i would be happy to add any feasible info into the project. 
btw are also wrapping up all samples we have and we have already rewritten some of them. e.g.
https://github.com/AgoraIO/Basic-Video-Call/tree/dev/3.0.0/Group-Video/OpenVideoCall-Android
this is not yet released as we are waiting for 3.0 sdk. maybe you can take a look at this (w/o 3.0 sdk you may not be able to compile though), but in this new version we have removed lots of unnecessary classes, e.g. worker thread.
You are also welcome to contribute any comments which may help us and all other developers. Hope this helps.

**Comment by smithaaron** [comment]
Ok, a concrete example:

```
public interface DuringCallEventHandler extends AGEventHandler {

    void onUserJoined(int uid);

    void onFirstRemoteVideoDecoded(int uid, int width, int height, int elapsed);

    void onJoinChannelSuccess(String channel, int uid, int elapsed);

    void onUserOffline(int uid, int reason);

    void onExtraCallback(int type, Object... data);
}
```

`DuringCallEventHandler`: Ok, this name is pretty self explanatory. It's for events which happen during a call I guess.

`onUserJoined`: is this the local user or a remote user?

`onFirstRemoteVideoDecoded:` The name is sufficient to give the developer an idea of when this happens, but some more explanation would be nice.

`onJoinChannelSuccess(String channel, int uid, int elapsed);`: Again, not clear if this is for the remote or local user. What is the elapsed parameter?

`onUserOffline`: same as above.

`onExtraCallback`: literally no idea what this might be for.

So this interface is a perfect example of where some document comments would let a developer understand what's going on much more quickly. e.g.

```
    /**
     * Called when local user successfully joins the channel.
     * @param channel Channel Name
     * @param uid User ID
     * @param elapsed Time in ms since joinChannel was called
     */
    void onJoinChannelSuccess(String channel, int uid, int elapsed);
```

I just think that if you're going to go to the bother of creating sample apps to help developers use the SDK, then you should make it as easy as possible for developers to understand what the apps are doing.

**Comment by plutoless** [comment]
thanks. very inspiring. i will see if we can adopt this fix ASAP. appreciate for your time writing all this.

**Comment by smithaaron** [comment]
Great news, thank you!
