### ISSUE TITLE
Live broadcast 1 second start after stop automatically?

### ISSUE THREAD

**Issue by Lalitchaudhary2** [AgoraIO/Basic-Video-Call#131]

**Comment by plutoless** [comment]
not sure what your request is. maybe some more details?

**Comment by Lalitchaudhary2** [comment]
if i starting my broadcast then first time it is broadcasted successfully ,but when i recreate it it getting stuck.

**Comment by plutoless** [comment]
what have you recreated? rtc engine instance? actuvity?

**Comment by Lalitchaudhary2** [comment]
I am use activity and after 10 minute  audience count api call he has no problem broadcasting stops?

**Comment by plutoless** [comment]
sorry i don't get you. what is audience count api? and what does "he has no problem broadcasting stops" mean?

**Comment by plutoless** [comment]
maybe you can provide a video recording
