### ISSUE TITLE
加入通道失败

### ISSUE THREAD

**Issue by aberson-xie** [AgoraIO/Basic-Video-Call#132]
仿照这个 示例 Basic-Video-Call/One-to-One-Video/Agora-Web-Tutorial-1to1/
加入通道时，报错Agora-SDK [ERROR]: [63CEC] Get server node failed [DYNAMIC_KEY_EXPIRED]
申请的token参照了 生产环境生成token的示例。

**Comment by plutoless** [comment]
你的token过期了，生成的时候注意一下生成期限

**Comment by aberson-xie** [comment]
好了，谢谢啦
