### ISSUE TITLE
Agora-Android-Tutorial-1to1 - Black local SurfaceView in first time.

### ISSUE THREAD

**Issue by TieuNhi95** [AgoraIO/Basic-Video-Call#138]
case : turn off internet
I copied code from sample for running. At the first time, surfaceView of local is black, after that, i replace new fragment and back, the local serfaceView has been displayed.
I also tested in your sample but still got the same result.

**Comment by plutoless** [comment]
you mean you run the demo while internet is off. and the first time you enter the room, the local display is black? Does it work if you have internet well running?

**Comment by TieuNhi95** [comment]
Yep.
When have internet, it only displayed when connect to room success.
I think local video must display immediate, don't need internet or depend connect state.

**Comment by plutoless** [comment]
if you want to see local view before join channel. you can use startPreview api.

**Comment by TieuNhi95** [comment]
to see local view, have more way to handle, but agora should have this.
IOS normal, only android got this, and when i go to new screen and return to previous screen, it displayed, so, i think it is bug.

**Comment by plutoless** [comment]
i see. i will help raise this to our sdk team. thanks for raising this.

**Comment by ps-jimmy** [comment]
Hello, any solution to the above black display issue?

**Comment by plutoless** [comment]
@ps-jimmy this issue is relevant to join channel w/o internet access. do you have the same problem?

**Comment by ps-jimmy** [comment]
I mean the local view does not display my video but the remote video dis
plays. Find in screenshoot attached.
![Screenshot_1588947065](https://user-images.githubusercontent.com/5190294/81414224-2b5d0780-9136-11ea-8047-9f15dd24a13e.png)

**Comment by ps-jimmy** [comment]
I mean the local view does not display my video but the remote video dis
plays. Find in screenshoot attached.

![WhatsApp Image 2020-05-08 at 14 30 29](https://user-images.githubusercontent.com/5190294/81415997-aaebd600-9138-11ea-9e5c-c6f71718e343.jpeg)

**Comment by plutoless** [comment]
have you granted camera permission? is there any chance you can help provide the sdk logs?
https://docs.agora.io/en/faqs/logfile# look here for how you can collect logs

**Comment by ps-jimmy** [comment]
Issue resolved, i have seen the reason ; i change the RENDER_MODE_HIDDEN to RENDER_MODE_FIT
mRtcEngine.setupLocalVideo(new VideoCanvas(videoSurface, VideoCanvas.RENDER_MODE_FIT, 0));

**Comment by plutoless** [comment]
usually render mode should not affect your video rendering. it will only make it fit to your video container. but anyway, glad it works for you :)
