### ISSUE TITLE
Update Windows sample?

### ISSUE THREAD

**Issue by SFoster84** [AgoraIO/Basic-Video-Call#143]
Hello,

Currently the windows tutorial is throwing this error when opening in VS2017 (or VS2019)
_The build tools for Visual Studio 2013 - Windows XP (v120_xp) cannot be found. Install Visual Studio 2013 - Windows XP (v120_xp) to build using the Visual Studio 2013 - Windows XP (v120_xp) build tools._

Would it be possible to supply an additional sample that's based on modern windows tools? 

Best Regards,
Scott

**Comment by sbd021** [comment]
You need set property of the project. Property -> Configuration Properties -> General -> Platform Toolset, select visual studio version you need.
