### ISSUE TITLE
Audio doesn't route via bluetooth headset

### ISSUE THREAD

**Issue by Dcosta2205** [AgoraIO/Basic-Video-Call#147]
Audio routing via bluetooth headset is not consistent. Sometimes the audio routes via bluetooth headset and sometimes on speaker. 

SDK versions: **v2.9.0 , v3.0.0**
Platform: **Android**
Android OS: 9
Device : OPPO A1k

**Comment by plutoless** [comment]
take a look at this https://github.com/AgoraIO/Flutter-SDK/issues/27#issuecomment-604407618
