### ISSUE TITLE
Landscape Support For iOS Group Call App

### ISSUE THREAD

**Issue by darshanRlogical1994** [AgoraIO/Basic-Video-Call#152]
Currently, existing demo only has supported the Portrait mode but we are eagerly waiting for landscape support in a group call and one to one call app. Can you please provide me landscape supported code for iOS(Swift).

Thanks in Advanced

**Comment by plutoless** [comment]
https://docs.agora.io/en/Voice/API%20Reference/oc/Classes/AgoraRtcEngineKit.html#//api/name/setVideoEncoderConfiguration:
check out this method, it has an orientationMode property, you can set it to landscape
