### ISSUE TITLE
3.0的sdk有办法把视频通话的延时降低到200ms以内吗

### ISSUE THREAD

**Issue by 298068845** [AgoraIO/Basic-Video-Call#153]
我手上有个用了声网sdk的遥控飞机的app，两台手机视频传输延时200ms以内，我自己开发的app降低分辨率码率延时都只能达到300~400ms左右（同样是这两台手机上运行）
是因为我用的是视频通话的sdk而不是直播的sdk吗？因为好像看到有个说法直播的sdk有个buff什么的，实时性会更高？

**Comment by plutoless** [comment]
如果要低于200ms应该需要特殊的sdk版本，要不您联系商务沟通一下
