### ISSUE TITLE
demo里的GridVideoViewContainer 当参会人数大于2的时候 视频页面依然是垂直布局 不是网格 导致人物显示不完全

### ISSUE THREAD

**Issue by GuoLiangjun123** [AgoraIO/Basic-Video-Call#158]
demo里的GridVideoViewContainer 当参会人数大于2的时候 视频页面依然是垂直布局 不是网格 导致人物显示不完全

**Comment by plutoless** [comment]
@GuoLiangjun123 您好，是open video call 还是 1-to-1?
