### ISSUE TITLE
Group-Video > OpenVideoCall-Android causes AGEventHandler.EVENT_TYPE_ON_APP_ERROR.

### ISSUE THREAD

**Issue by wann2** [AgoraIO/Basic-Video-Call#16]
Hi, 

Basic-Video-Call > Group-Video > OpenVideoCall-Android

I play the upper program with two different smartphones.
I test it in good network connect of both wifi and LTE.

But I get always the following error.
AGEventHandler.EVENT_TYPE_ON_APP_ERROR (No network connection, please check the network settings)

**Comment by cmder** [comment]
Did u use the VPN? If so, u can turn off it and try again.

**Comment by wann2** [comment]
I am not using VPN.
For test, I am using general and Wifi or LTE and the network bandwidth is wide and good.
Nevertherless, AGEventHandler.EVENT_TYPE_ON_APP_ERROR (No network connection, please check the network settings) always happen.
Could you show me how to extract a log of AgoraSDK?
I don't know how to extract it.

**Comment by guohai** [comment]
You can use `setLogFile` to save logs to your storage card
