### ISSUE TITLE
[Windows SDK] setVideoDevice is not working

### ISSUE THREAD

**Issue by BobDLA** [AgoraIO/Basic-Video-Call#161]
Test on SDK3.0.0, 2.9.3  MFC and QT demo.
The API of "setVideoDevice" is not working,  always cap camera 0. 
Is this a bug?

**Comment by plutoless** [comment]
any logs? what is the return value for this api call? you may specify an invalid deviceId which makes you fail to change using device

**Comment by BobDLA** [comment]
@plutoless  here is the log. If only connect one camera, any of the two cameras  could work. 
Could you please verify the function also?

INFO    18:34:32:488  20264; [rp] ["rtc.addref_media_engine"]
INFO    18:34:32:488  20264; addRef of media engine, ref=1
INFO    18:34:32:488  20264; [che] create chat engine, ctx:00000000
INFO    18:34:32:488  20264; [MYDEBUG] large group call false
INFO    18:34:32:488  20264; setupMediaEngineMode(): Hardware decoding false
INFO    18:34:32:488  20264; agora::media::MediaEngineParameterCollection::setupMediaEngineMode: mode 3
WARN    18:34:32:488  20264; agora::media::MediaEngineParameterCollection::setupMediaEngineMode: skip updateClientRole as audio engine not created, mode 3
INFO    18:34:32:489  20264; engine git commit version:14bf5ef7f and branch:(HEAD
INFO    18:34:32:490  20264; output: kPlatformDefaultAudio
INFO    18:34:32:490  20264; [WIN_CORE] +++++++Code block begins for checking CoreAudio properties++++++
INFO    18:34:32:490  20264; AgoraRTC::AudioDeviceNotificationWindows::AudioDeviceNotificationWindows created
INFO    18:34:32:493  20264; [WIN_CORE] ===================Render Devices Enumeration===================
INFO    18:34:32:493  20264; [WIN_CORE] #rendering endpoint devices (counting all): 5
INFO    18:34:32:493  20264; [WIN_CORE] ++Endpoint  0:
INFO    18:34:32:493  20264; [WIN_CORE] ID string    : {0.0.0.00000000}.{033f7e7c-4faf-4675-bf49-af4dee78a7f1}
INFO    18:34:32:493  20264; [WIN_CORE] friendly name: "HDMI (2- NVIDIA High Definition Audio)"
INFO    18:34:32:493  20264; [WIN_CORE] state (0x1)  : *ACTIVE*
INFO    18:34:32:493  20264; [WIN_CORE] ++Endpoint  1:
INFO    18:34:32:493  20264; [WIN_CORE] ID string    : {0.0.0.00000000}.{29af77cf-a62c-4504-8e02-3411cdee4820}
INFO    18:34:32:493  20264; [WIN_CORE] friendly name: "NVIDIA Output (2- NVIDIA High Definition Audio)"
INFO    18:34:32:493  20264; [WIN_CORE] state (0x8)  : UNPLUGGED
INFO    18:34:32:493  20264; [WIN_CORE] ++Endpoint  2:
INFO    18:34:32:493  20264; [WIN_CORE] ID string    : {0.0.0.00000000}.{6f76014e-94c0-4ec3-8be6-07831bf4e252}
INFO    18:34:32:494  20264; [WIN_CORE] friendly name: "扬声器 (Realtek(R) Audio)"
INFO    18:34:32:494  20264; [WIN_CORE] state (0x1)  : *ACTIVE*
INFO    18:34:32:494  20264; [WIN_CORE] ++Endpoint  3:
INFO    18:34:32:494  20264; [WIN_CORE] ID string    : {0.0.0.00000000}.{7e586b15-dba9-43de-a458-2556a34969f9}
INFO    18:34:32:494  20264; [WIN_CORE] friendly name: "扬声器 (NoMachine Microphone Adapter)"
INFO    18:34:32:494  20264; [WIN_CORE] state (0x1)  : *ACTIVE*
INFO    18:34:32:494  20264; [WIN_CORE] ++Endpoint  4:
INFO    18:34:32:494  20264; [WIN_CORE] ID string    : {0.0.0.00000000}.{dce684c4-1ac2-44ab-a967-e9e9a8ffc9d6}
INFO    18:34:32:494  20264; [WIN_CORE] friendly name: "NVIDIA Output (2- NVIDIA High Definition Audio)"
INFO    18:34:32:494  20264; [WIN_CORE] state (0x8)  : UNPLUGGED
INFO    18:34:32:494  20264; [WIN_CORE] =========================EnumDeviceEnd==========================
INFO    18:34:32:498  20264; [WIN_CORE] ==================Capture Devices Enumeration===================
INFO    18:34:32:498  20264; [WIN_CORE] #capturing endpoint devices (counting all): 4
INFO    18:34:32:498  20264; [WIN_CORE] ++Endpoint  0:
INFO    18:34:32:498  20264; [WIN_CORE] ID string    : {0.0.1.00000000}.{7a8e15e7-3449-455b-a3f4-e434b88f104a}
INFO    18:34:32:498  20264; [WIN_CORE] friendly name: "麦克风 (USB Microphone)"
INFO    18:34:32:498  20264; [WIN_CORE] state (0x1)  : *ACTIVE*
INFO    18:34:32:498  20264; [WIN_CORE] ++Endpoint  1:
INFO    18:34:32:498  20264; [WIN_CORE] ID string    : {0.0.1.00000000}.{817a01d0-2203-4d0e-bc08-c7396a5a19a4}
INFO    18:34:32:499  20264; [WIN_CORE] friendly name: "麦克风 (NoMachine Microphone Adapter)"
INFO    18:34:32:499  20264; [WIN_CORE] state (0x1)  : *ACTIVE*
INFO    18:34:32:499  20264; [WIN_CORE] ++Endpoint  2:
INFO    18:34:32:499  20264; [WIN_CORE] ID string    : {0.0.1.00000000}.{a6350b81-60d7-43ed-a356-792af542075d}
INFO    18:34:32:499  20264; [WIN_CORE] friendly name: "麦克风 (Realtek(R) Audio)"
INFO    18:34:32:499  20264; [WIN_CORE] state (0x1)  : *ACTIVE*
INFO    18:34:32:499  20264; [WIN_CORE] ++Endpoint  3:
INFO    18:34:32:499  20264; [WIN_CORE] ID string    : {0.0.1.00000000}.{ff651ffa-f2de-48e5-a0b1-d5afebb70d4b}
INFO    18:34:32:499  20264; [WIN_CORE] friendly name: "立体声混音 (Realtek(R) Audio)"
INFO    18:34:32:499  20264; [WIN_CORE] state (0x2)  : DISABLED
INFO    18:34:32:499  20264; [WIN_CORE] =========================EnumDeviceEnd==========================
INFO    18:34:32:506  20264; [WIN_CORE] *** Windows Core Audio is supported ***
INFO    18:34:32:506  20264; [WIN_CORE] ++++++++Code block ends for checking CoreAudio properties++++++++
INFO    18:34:32:506  20264; audio jitterbuffer new smooth
INFO    18:34:32:506   3680; Thread with name:AudioFileDecoderThread started 
INFO    18:34:32:506  20264; OutputMixer: start audio file decoder thread successfully
INFO    18:34:32:506  20264;   OS info: Microsoft  (build 9200), 64-bit
INFO    18:34:32:511  20264; [WIN_CORE] Set playout device on Windows by Windows Device Type (-2): friendly name: "HDMI (2- NVIDIA High Definition Audio)"
INFO    18:34:32:524  20264; [WIN_CORE] Set recording device on Windows by Windows Device Type (-2): friendly name: "麦克风 (USB Microphone)"
INFO    18:34:32:529  20264; StereoPlayoutIsAvailable(), output: available=1
Local Date: 5Ԃ 06 2020 Local Time: 18:34:32
Build info: Mar  4 2020 16:56:43 r

INFO    18:34:32:529  20264; StereoRecordingIsAvailable(), output: available=1
INFO    18:34:32:529   9336; Thread with name:EngineMonitorThread started 
INFO    18:34:32:529  20264; RegisterVolumeNotify
WARN    18:34:32:529  20264; agora::media::AudioEngineWrapper::enableLocalRecordingDevice: enable 1 already set
INFO    18:34:32:529  20264; setMuteStatus, muted: On
INFO    18:34:32:529  20264; setMuteOutput, muted: false
INFO    18:34:32:529   6112; Thread with name:AudioAsyncTask started 
INFO    18:34:32:529  20264; Audio Engine Init success, mSpecMode 3
INFO    18:34:32:529  20264; PipelineManager::SetDest  engine = 0BA49268
INFO    18:34:32:529  20264; agora::media::VideoEngine::CreateVideoSendTrack
INFO    18:34:32:530  18272; Thread with name:VideoAsyncTask started 
INFO    18:34:32:530  20264; agora::media::VideoEngine::init: feature prerotation enabled
INFO    18:34:32:530  20264; Agora Engine video codec set to standard mode role mode 3
INFO    18:34:32:530  20264; Agora Engine video codec index 1
INFO    18:34:32:530  20264; Agora Engine video stream type = 0
INFO    18:34:32:530  17548; Thread with name:VideoEncodeThread started 
INFO    18:34:32:530  20264; Device type: 3004
INFO    18:34:32:530  20264; Hardware encoding false
INFO    18:34:32:530  20264; last unique frame idx: -1 - -1
INFO    18:34:32:530  20264; Device type: 3004
INFO    18:34:32:530  20264; EncoderWrapper::Create hardware_ = 0, hardware_low_ = 0
INFO    18:34:32:530  20264; low bit rate limit 3758096384
INFO    18:34:32:530  20264; dont need to increase unique frame idx
INFO    18:34:32:530  20264; the init unique frame idx: -1 - -1
INFO    18:34:32:530   8124; Thread with name:VideoProcessThread started 
INFO    18:34:32:530  20264; agora::media::VideoEngine::setCodec: index=1 width=640 height=360 framerate=15
INFO    18:34:32:530  20264; agora::media::VideoEngine::setCodec: Intra Request = 0
INFO    18:34:32:530  17548; Thread with name:VideoEncodeThread stopped
INFO    18:34:32:531   4376; Thread with name:VideoEncodeThread started 
INFO    18:34:32:531  20264; Device type: 3004
INFO    18:34:32:531  20264; Hardware encoding false
INFO    18:34:32:531  20264; last unique frame idx: -1 - -1
INFO    18:34:32:531  20264; Device type: 3004
INFO    18:34:32:531  20264; EncoderWrapper::Create hardware_ = 0, hardware_low_ = 0
INFO    18:34:32:531  20264; low bit rate limit 3758096384
INFO    18:34:32:531  20264; set last big unique frame idx: -1
INFO    18:34:32:531  20264; set last small unique frame idx: -1
INFO    18:34:32:531  20264; the init unique frame idx: -1 - -1
INFO    18:34:32:531  20264; agora::media::VideoEngine::h264WebInteropEnable: enable 1
INFO    18:34:32:531  20264; agora::media::VideoEngine::setCaptureDevice: index=0
INFO    18:34:32:541  20264; Device Enum:Device Name:Integrated Camera
INFO    18:34:32:938  20264; Device Enum:Device Name:USB2.0 Camera
INFO    18:34:32:950  20264; VideoSendTrackImpl::agora::VideoSendTrackImpl::UpdateCapturer capturer=0B812718
INFO    18:34:32:950  20264; agora::media::VideoEngine::CreateVideoCapturer: interface=0B812718
INFO    18:34:32:950  20264; agora::media::VideoEngine::setMaxVideoBitrate: max bitrate=0
INFO    18:34:32:950  20264; [setupParameterObservers:1636] setting of localViewMirrorSetting[] is invalid!
INFO    18:34:32:950  20264; [agora::media::VideoEngine::setupParameterObservers::<lambda_39501f22a8d8aedd722eda21c873c442>::operator ():1662] m_context.parameters.video.mirrorMode: json is invalid! value:00000000
INFO    18:34:32:950  20264; Setting video fec method 2, real using 2
INFO    18:34:32:950  20264; SetBandwidthAgressiveLevel to 3.
INFO    18:34:32:950  20264; dynamic sending rate control set to 2.

INFO    18:34:32:950  20264; videoEngine created and initialize here
INFO    18:34:32:950  20264; agora::media::VideoEngine::CreateVideoSendTrack
INFO    18:34:32:950  20264; [MIO] updateCapturer: (00000000), type:(1)
INFO    18:34:32:950  20264; agora::media::VideoEngine::CreateAgoraDefaultCapture: type=0
INFO    18:34:32:950  20264; VideoSendTrackImpl::agora::VideoSendTrackImpl::UpdateCapturer capturer=0B812718
WARN    18:34:32:950  20264; VideoSendTrackImpl::agora::VideoSendTrackImpl::UpdateCapturer, Ignore updating the same capturer
INFO    18:34:32:950  20264; [MIO] updateLocalRender: (00000000), type:(1)
INFO    18:34:32:950  20264; agora::media::VideoEngine::CreateAgoraDefaultRender
INFO    18:34:32:950  20264; VideoSendTrackImpl::agora::VideoSendTrackImpl::UpdateRenderer, renderer=0B6F0E80
INFO    18:34:32:950  20264; agora::media::VideoEngine::CreateVideoRenderer: interface=0B6F0E80
INFO    18:34:32:950  20264; [MIO] video send track prepared !!
INFO    18:34:32:950  20264; VideoSendTrackImpl::agora::VideoSendTrackImpl::UpdateCapturer capturer=0B812718
WARN    18:34:32:950  20264; VideoSendTrackImpl::agora::VideoSendTrackImpl::UpdateCapturer, Ignore updating the same capturer
INFO    18:34:32:950  20264; [che] applyVideoProfile: 640x360 15 fps  -1 minFps 400 kbps, min -1 kbps orientationMode 0 degradationPrefer 0 mirrorMode 0
INFO    18:34:32:950  20264; agora::media::VideoEngine::validateVideoParameters: validate video parameters resolution 640x360, fps 15, rate 400000
INFO    18:34:32:950  20264; agora::media::VideoEngine::enableMirrorMode: enable=0
INFO    18:34:32:950  20264; agora::media::VideoEngine::setMaxVideoBitrate: max bitrate=400000
INFO    18:34:32:950  20264; agora::media::VideoEngine::_setCodecRates: set frame rate to 15
INFO    18:34:32:950  20264; agora::media::VideoEngine::setCodec: index=1 width=640 height=360 framerate=15
INFO    18:34:32:950  20264; agora::media::VideoEngine::setCodec: Intra Request = 0
INFO    18:34:32:950   4376; Thread with name:VideoEncodeThread stopped
INFO    18:34:32:951  12312; Thread with name:VideoEncodeThread started 
INFO    18:34:32:951  20264; Device type: 3004
INFO    18:34:32:951  20264; Hardware encoding false
INFO    18:34:32:951  20264; last unique frame idx: -1 - -1
INFO    18:34:32:951  20264; Device type: 3004
INFO    18:34:32:951  20264; EncoderWrapper::Create hardware_ = 0, hardware_low_ = 0
INFO    18:34:32:951  20264; low bit rate limit 0
INFO    18:34:32:951  20264; set last big unique frame idx: -1
INFO    18:34:32:951  20264; set last small unique frame idx: -1
INFO    18:34:32:951  20264; the init unique frame idx: -1 - -1
INFO    18:34:32:951  20264; SetTargetWidthHeight width:640, height:360
INFO    18:34:32:951  20264; agora::media::VideoEngine::_setCodecResolution: set to 640 x 360
INFO    18:34:32:951  20264; Set broadcast min br to -1.
INFO    18:34:32:951  20264; [che] chat engine initialized
INFO    18:34:32:951  20264; [time] process EngineInitialize takes 463
INFO    18:34:32:951  20264; [rp] res: {"rtc.addref_media_engine":0} 
INFO    18:34:32:952  20264; [rp] ["che.video.local.enum_camera"]
INFO    18:34:32:962  20264; Device Enum:Device Name:Integrated Camera
INFO    18:34:33:230  20264; Device Enum:Device Name:USB2.0 Camera
INFO    18:34:33:237  20264; [rp] res: {"che.video.local.enum_camera":[[0,"\\\\?\\usb#vid_04ca&pid_7070&mi_00#6&ded6fe1&0&0000#{65e8773d-8f56-11d0-a3b9-00a0c9223196}\\global","Integrated Camera"],[1,"\\\\?\\usb#vid_1e4e&pid_0109&mi_00#6&3425799b&0&0000#{
INFO    18:34:33:237  20264; [rp] {"che.video.local.camera_id":"\\\\?\\usb#vid_1e4e&pid_0109&mi_00#6&3425799b&0&0000#{65e8773d-8f56-11d0-a3b9-00a0c9223196}\\global"}
INFO    18:34:33:237  20264; agora::media::VideoEngine::setCaptureDevice: deviceId=\\?\usb#vid_1e4e&pid_0109&mi_00#6&3425799b&0&0000#{65e8773d-8f56-11d0-a3b9-00a0c9223196}\global
INFO    18:34:33:237  20264; agora::media::VideoEngine::setCaptureDevice: index=1
INFO    18:34:33:237  20264; VideoSendTrackImpl::agora::VideoSendTrackImpl::UpdateCapturer capturer=0B812718
WARN    18:34:33:237  20264; VideoSendTrackImpl::agora::VideoSendTrackImpl::UpdateCapturer, Ignore updating the same capturer
INFO    18:34:33:237  20264; [rp] ["rtc.delref_media_engine"]
INFO    18:34:33:237  20264; delRef of media engine, ref=0
INFO    18:34:33:237  20264; [che] chat engine destroying
INFO    18:34:33:237  20264; agora::media::VideoEngine::stopLocalRender
INFO    18:34:33:237  20264; agora::media::VideoEngine::stopLocalRender success
WARN    18:34:33:237  20264; agora::media::VideoEngine::stopCapture: VideoEngine haven't startCapture
INFO    18:34:33:237  20264; agora::media::VideoEngine::stopRemoteRender
INFO    18:34:33:237  20264; [che] stopCall begins
INFO    18:34:33:237  20264; [che] stop call returns -1, elapsed 0
INFO    18:34:33:237  20264; VideoSendTrackImpl::agora::VideoSendTrackImpl::UpdateCapturer capturer=00000000
INFO    18:34:33:237  20264; agora::media::VideoEngine::CreateVideoCapturer: interface=00000000
INFO    18:34:33:237  20264; VideoSendTrackImpl::agora::VideoSendTrackImpl::UpdateRenderer, renderer=00000000
INFO    18:34:33:237  20264; agora::media::VideoEngine::CreateVideoRenderer: interface=00000000
INFO    18:34:33:237  20264; agora::media::VideoEngine::stopLocalRender: Cannot stop renderer -1 (not exist)
INFO    18:34:33:237  20264; agora::media::VideoEngine::stopRemoteRender
WARN    18:34:33:237  20264; agora::media::VideoEngine::stopCapture: VideoEngine haven't startCapture
INFO    18:34:33:237   8124; Thread with name:VideoProcessThread stopped
INFO    18:34:33:238  18272; Thread with name:VideoAsyncTask stopped
INFO    18:34:33:238  20264; PipelineManager::SetDest  engine = 00000000
WARN    18:34:33:238  20264; agora::media::VideoEngine::terminate: VideoEngine haven't init
INFO    18:34:33:238  20264; [DEBUGG] ViERenderManager Destructor, engine_id: 0
INFO    18:34:33:238  12312; Thread with name:VideoEncodeThread stopped
INFO    18:34:33:238  20264; AgoraCameraCapture::agora::AgoraCameraCapture::Dispose
INFO    18:34:33:238   6112; Thread with name:AudioAsyncTask stopped
INFO    18:34:33:238   9336; Thread with name:EngineMonitorThread stopped
INFO    18:34:33:239   3680; Thread with name:AudioFileDecoderThread stopped
INFO    18:34:33:239  20264; AgoraRTC::AudioDeviceNotificationWindows::~AudioDeviceNotificationWindows destroyed
INFO    18:34:33:239  20264; [che] chat engine destroyed
INFO    18:34:33:239  20264; [rp] res: {"rtc.delref_media_engine":0}

**Comment by plutoless** [comment]
looks like the video engine starts destroying itself when you call setVideoDevice. have you done any changes to the demo or you are just running as it is?

**Comment by BobDLA** [comment]
Just running as it is.

**Comment by sbd021** [comment]
After setVideoDevice(IVideoDeviceManager::setDevice), you need to  click the button "confirm".

**Comment by BobDLA** [comment]
> After setVideoDevice(IVideoDeviceManager::setDevice), you need to click the button "confirm".

where is the confirm  button?
![image](https://user-images.githubusercontent.com/3804610/81261123-0ac97a80-906e-11ea-87b7-096f527e8694.png)

**Comment by sbd021** [comment]
Click "Test" button,  then you will see the device dialog. Select camera and click "Confirm" button.
