### ISSUE TITLE
[Windows SDK] onVideoDeviceStateChanged call back is not working

### ISSUE THREAD

**Issue by BobDLA** [AgoraIO/Basic-Video-Call#162]
Test on SDK 3.0.0  , QT and MFC demo.
No onVideoDeviceStateChanged  callback after unplug the external camera.
And check the AgoraSDK.log , no log message output also.
Is this a bug?

**Comment by sbd021** [comment]
You need to set RtcEngineContext::context a HWND variable, when calling IRtcEngine::initialize. Get details here https://docs.agora.io/cn/Video/API%20Reference/cpp/structagora_1_1rtc_1_1_rtc_engine_context.html
