### ISSUE TITLE
Calling screen on One to One call for web

### ISSUE THREAD

**Issue by nikolas310** [AgoraIO/Basic-Video-Call#163]
is there any documentation on calling screen play ringtone and receive like facebook calling

**Comment by plutoless** [comment]
https://github.com/AgoraIO-usecase/video-calling

**Comment by nikolas310** [comment]
@plutoless have any docs on web version video calling

**Comment by plutoless** [comment]
the web version is up coming. 
a beta version is available at https://github.com/AgoraIO-Usecase/Video-Calling/tree/dev/web
but it's still under test, i suggest you wait till we merge it back to master.
