### ISSUE TITLE
[swiftUI] 當使用 NavigationLink 顯示畫面時 看不到視訊畫面

### ISSUE THREAD

**Issue by c941010623** [AgoraIO/Basic-Video-Call#164]
我是用 SwiftUI 開發
但是我利用 NavigationLink 去轉畫面的時候
看不到對方的視訊。
有聲音 但是沒畫面

**Comment by Steven364** [comment]
?? 有人嗎～～～

**Comment by plutoless** [comment]
We will work on a quick test on this.

**Comment by c941010623** [comment]
好的，因為這對我目前的專案很重要。

**Comment by c941010623** [comment]
我目前為主畫面 => NavigationLink(好友清單) => 點選視訊通話 => NavigationLink(VideoView) => 灰色一片 (使用範例的 Code)

**Comment by c941010623** [comment]
抱歉，我解決了，原來不能放在最下層
需要放在第一層然後利用 NavigationLink 的 isActive 開關。

主畫面 => NavigationLink(好友清單) => 點選視訊通話 => active = true 
主畫面 => NavigationLink(VideoView, isActive: $active) => 正常顯示

**Comment by PRWrl** [comment]
@c941010623 简单测试了 NavigationLink，可以正常显示对方的视频，参看测试代码(实例代码中没有处理点击返回按钮退出频道)：  https://github.com/AgoraIO/Basic-Video-Call/commit/ca6b98336b29db1edc42d002274830c372a31a40

方便的话可以贴下具体的代码，帮助我们更好地定位问题
