### ISSUE TITLE
[AB1A9] Get server node failed [INVALID_VENDOR_KEY] https://webrtc2-ap-web-1.agora.io/api/v1 INVALID_VENDOR_KEY

### ISSUE THREAD

**Issue by shaileshkumarcs** [AgoraIO/Basic-Video-Call#166]

**Comment by plutoless** [comment]
it usually means you are not using correct appid or token.

**Comment by plutoless** [comment]
please read the readme or corresponding samples to ensure you have provided all necessary info

**Comment by shaileshkumarcs** [comment]
I checked the readme file. Now I am getting this "[35D7F] Get server node failed [NO_AUTHORIZED]".

Can you please help

**Comment by shaileshkumarcs** [comment]
@plutoless Please guide me...

**Comment by plutoless** [comment]
have you provided a token when joining channel?

**Comment by shaileshkumarcs** [comment]
Yes, I used PHP code to generate the token.
Here is the link 

https://github.com/AgoraIO/Tools/tree/master/DynamicKey/AgoraDynamicKey/php

**Comment by plutoless** [comment]
could you pls provide the token you generated, together with the channel and uid you used to join the channel?

**Comment by shaileshkumarcs** [comment]
Token with int uid: 006ce00315044a64c65be438afaa69d3b48IADz9x8YXsZ7bLL6+E4+eEhb+37A+dilELgfX8oXX14i3kHeK5tXoFHlIgDfqgAARKK3XgQAAQDUXrZeAwDUXrZeAgDUXrZeBADUXrZe Token with user account: 006ce00315044a64c65be438afaa69d3b48IAC5LElPKRFCTshz4Hh+DXAL1HyMGLkWrippeYLYVuhzS0HeK5tXoFHlIgCyNAAARKK3XgQAAQDUXrZeAwDUXrZeAgDUXrZeBADUXrZe

**Comment by plutoless** [comment]
@shaileshkumarcs what is the channel and uid you used to join channel which failed?

**Comment by shaileshkumarcs** [comment]
Finally, I got solutions. Actually I was passing UID: "1213231", It's accepting "0", the role also accepting "0",

Now it's working.
