### ISSUE TITLE
VideoRenderIosGles_65535 (62): EXC_BAD_ACCESS (code=1, address=0x0) in iOS

### ISSUE THREAD

**Issue by Komal2905** [AgoraIO/Basic-Video-Call#167]
I am using this library to make video call.
One on one call Is happening without any problem
but when we try to add new user to ongoing video call, I get this error and it crash
Video call is between iOS and android device and we are trying to add new android device after some time

we get this error
VideoRenderIosGles_65535 (62): EXC_BAD_ACCESS (code=1, address=0x0) 

video setting is
        agoraKit.setVideoEncoderConfiguration(AgoraVideoEncoderConfiguration(size: AgoraVideoDimension640x360,
                                                                             frameRate: .fps15,
                                                                             bitrate: AgoraVideoBitrateStandard,
                                                                             orientationMode: .fixedPortrait))

**Comment by plutoless** [comment]
is this 100% reproducible? what have you changed?

**Comment by Komal2905** [comment]
@plutoless  Yes, Its is reproducible
I changed orientationMode : fixedPortrait
this is iOS setting
renderMode = .fit
size: AgoraVideoDimension640x360
frameRate: .fps15
bitrate: AgoraVideoBitrateStandard
orientationMode: .fixedPortrait

Following is android setting
VideoEncoderConfiguration.VD_640x360
VideoEncoderConfiguration.FRAME_RATE.FRAME_RATE_FPS_15
VideoEncoderConfiguration.STANDARD_BITRATE
VideoEncoderConfiguration.ORIENTATION_MODE.ORIENTATION_MODE_FIXED_PORTRAIT

Call between iOS and Android is smooth . but when Android device try to add third person in ongoing call it crash on iOS side

**Comment by Komal2905** [comment]
@plutoless I have recently update to Xcode 11

**Comment by plutoless** [comment]
@Komal2905 we have some customers having similar issues after upgrading to Xcode 11 and iOS13, we are still investigating, please keep an eye on this thread for potential updates

**Comment by Komal2905** [comment]
@plutoless Any ETA for it?

**Comment by plutoless** [comment]
@Komal2905 not yet. it seems not that relevant to our SDK and our engineering team is still investigating

**Comment by plutoless** [comment]
@Komal2905 sorry for late reply. could you pls double check if you are reusing the canvas item, or not cleaning its binding after using it?
