### ISSUE TITLE
error: package VideoEncoderConfiguration does not exist

### ISSUE THREAD

**Issue by adityam263** [AgoraIO/Basic-Video-Call#17]
I tried to run the programme after inserting my app id and compile 'io.agora.rtc:full-sdk:2.2.0' still getting error   error: package VideoEncoderConfiguration does not exist

i have attached Screenshot of screen 

![screenshot 5](https://user-images.githubusercontent.com/33219421/49503164-d3650600-f89c-11e8-8a55-f5e303816590.png)

**Comment by PRWrl** [comment]
hi @adityam263 

VideoEncoderConfiguration is a new api from version 2.3.0.

You can get the latest sdk from [Developer Center](https://docs.agora.io/en/Video/downloads), which is version 2.3.1 currently
