### ISSUE TITLE
 Cannot read property 'appendChild' of null

### ISSUE THREAD

**Issue by akashmanan** [AgoraIO/Basic-Video-Call#174]
<img width="1277" alt="Screenshot 2020-05-19 at 12 39 44 PM" src="https://user-images.githubusercontent.com/65590206/82296719-3da93200-99cf-11ea-8f3a-3ecdc393cd25.png">
I got this issue in one to one web video call. is any mistake in integration ? sometime video calling
works but some time i got this error.

**Comment by plutoless** [comment]
this usually happens when you try to play a video on a non-existing dom.
did you make any change to the demo?

**Comment by akashmanan** [comment]
I have issue in joinchannel. videocalling works well at one side but another side can't able to see/hear another user. 
I got publish stream failed with error "NO_TRACK_IN_STREAM" in console. issue in join channel by remote user

**Comment by yoreland** [comment]
@akashmanan 
Can you confirm the remote user is using same appid and same channel name?
if there is no issues above, can you please share the detailed console log?

**Comment by akashmanan** [comment]
remote user is using same appid and same channel name i can see and hear another user but he can't see/hear me. at my side two uid show join channel successfully and another side only one uid.

**Comment by yoreland** [comment]
is that possible to share a link of your page to reproduce this issue?

**Comment by akashmanan** [comment]
<img width="1051" alt="Screenshot 2020-06-04 at 1 11 35 PM" src="https://user-images.githubusercontent.com/65590206/83729453-42bfdf80-a665-11ea-8e40-d05179ec6e29.png">

console at another side

**Comment by plutoless** [comment]
according to the log, 38322's video/audio is muted.
