### ISSUE TITLE
I didn't understand part of a sample app's setup instructions

### ISSUE THREAD

**Issue by david-mears-dfe** [AgoraIO/Basic-Video-Call#179]
In [this](https://github.com/AgoraIO/Basic-Video-Call/tree/master/Group-Video/OpenVideoCall-Web) sample app, I am told to "Generate a temp Access Token (valid for 24 hours) from dashboard page with given channel name, save for later use."

I didn't (and don't) understand the phrase "dashboard page with given channel name" so it took me a long time to find the right place on agora.io. Please add a screenshot to show where I can find the temporary Access Token. You could also say that the temp token can be created under 'Features' which can be found after clicking 'Edit' on a project in the Project Management section.

**Comment by plutoless** [comment]
thanks for the suggestion. i will update it to make it easier to understand.
