### ISSUE TITLE
How to initiate the connecting / ringing call to other person?

### ISSUE THREAD

**Issue by hassan31** [AgoraIO/Basic-Video-Call#182]
Hi, first of all, thank you very much for such a nice and easy to use video calling SDK. It is awesome.
I run the demo project on my devices and working perfectly. My question is to related the Initial call ringing and connecting process. How can I achieve this behavior like other applications or native calls? Is there anything related to the demo or can you refer me some example in this regard?

Also if the application is in the background and another person calls me, do this SDK handles this behavior as well?

Thanks in advance.

**Comment by plutoless** [comment]
https://github.com/AgoraIO-usecase/video-calling
