### ISSUE TITLE
How to remove individual users in the channel in web javascriptSDK

### ISSUE THREAD

**Issue by kumargowdaa** [AgoraIO/Basic-Video-Call#184]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kumargowdaa** [comment]
@guohai @plutoless @zontan

thanks in advance

**Comment by yoreland** [comment]
Kumar, kicking a user currently supported on restful API:
https://docs.agora.io/en/Agora%20Platform/dashboard_restful_communication
**BaseUrl/v1/kicking-rule/**
Do you think this help here?

**Comment by kumargowdaa** [comment]
@yoreland thanks for your reply. i am not able to access the APIs, please help me on this

![image](https://user-images.githubusercontent.com/17003296/83595811-a1f7f400-a580-11ea-8fe6-eaa92c544680.png)

**Comment by yoreland** [comment]
@kumargowdaa do you mean you can't access the document url, or you can't use restfulAPI in your app?

**Comment by kumargowdaa** [comment]
@yoreland 
yes i am not able to access the document url and not able to get the response as mentioned in document

![image](https://user-images.githubusercontent.com/17003296/83597650-76c3d380-a585-11ea-8ae8-7d5a7e3395eb.png)

**Comment by yoreland** [comment]
@kumargowdaa if you are in internal network, can you try with some other network, for example 4g?
for 401 error, can you check if the user has proper permission to use restful api. Can also please check the api-key and secret are valid (you should get them from console -> right top corner's user menu -> restful api -> customer ID and certificate)

**Comment by kumargowdaa** [comment]
@yoreland the customer ID and certificate are valid i took it from console only,
can you please make one request in postman and  show me an example.

thank you

**Comment by yoreland** [comment]
<img width="809" alt="image" src="https://user-images.githubusercontent.com/8169775/83603141-738d0f80-a5a6-11ea-9117-1003eaf5fb09.png">
You could try to fill your customer ID and secret in Authorization tab of post man instead headers

**Comment by kumargowdaa** [comment]
@yoreland 
thank you so much its worked for me
