### ISSUE TITLE
Support for Hololens 2 (UWP, arm64)

### ISSUE THREAD

**Issue by joaocc** [AgoraIO/Basic-Video-Call#188]
**Is your feature request related to a problem? Please describe.**
We would like to be able to use AgoraIO video calls on Hololens 2 (UWP, arm64, Unity3D)

**Additional context**
https://docs.agora.io/en/Video/product_video#compatibility only lists "x86, x86_64" under Unity/Windows.

**Comment by plutoless** [comment]
sorry we don't have an official support for now.

**Comment by joaocc** [comment]
Any plans on when that could be available? thx

**Comment by plutoless** [comment]
i will transfer this requirement to our PM team. you may come back check the progress in Q4 maybe.

**Comment by ltwlf** [comment]
Any news here? This is for us a show stopper!

**Comment by ttkrpink** [comment]
So, Hololens is not supported yet?

**Comment by FarazFolio3** [comment]
Would like to know this as well, its been a couple of years is holo lens support coming 
@ttkrpink @ltwlf @joaocc if you guys have an alternate solution please let me know
