### ISSUE TITLE
Question: How do you publish additional data with the stream

### ISSUE THREAD

**Issue by hjhimanshu01** [AgoraIO/Basic-Video-Call#191]
Would love to have some additional data across the streams published, (eg: name of the person who joined etc) though couldn't find a way to do that. Is there a way to do it?

**Comment by yoreland** [comment]
Hi, you may be interested with Agora's RTM sdk:
https://docs.agora.io/en/Real-time-Messaging/product_rtm?platform=All%20Platforms

**Comment by hjhimanshu01** [comment]
@yoreland , Awesome! Thanks for the help!
