### ISSUE TITLE
How many maximum users can connect as an audiences in single call? 

### ISSUE THREAD

**Issue by jalpaiCreative** [AgoraIO/Basic-Video-Call#193]
I want to make live like facebook live, where number of audience will connect. 
So i wants to how many users can connect for a single live?

**Comment by yoreland** [comment]
you could refer this page:
https://docs.agora.io/en/Interactive%20Broadcast/product_live?platform=All%20Platforms

Host Capacity | 17 users
Audience Capacity | **One million users**
