### ISSUE TITLE
Blazor (webassembly) and Agora web SDK.

### ISSUE THREAD

**Issue by sowsan** [AgoraIO/Basic-Video-Call#197]
Blazor (webassembly) and Agora web SDK.

Do you have any sample to work with Blazor and Agora Web SDK? I am trying but the video is not rendering. I am trying with the localVideo first by following the basic sample available in the demo section in this repo. All I can see that script executing and video are enabled but no video element showing in the UI.

https://docs.microsoft.com/en-us/aspnet/core/blazor/call-javascript-from-dotnet?view=aspnetcore-3.1#call-a-void-javascript-function

**Comment by yoreland** [comment]
Can you upload your sample project for verifying?

**Comment by Vikas8881** [comment]
did you find any solution? because i am also stuck on same
