### ISSUE TITLE
OpenVideoCall-Linux 的英文开发环境描述有误

### ISSUE THREAD

**Issue by yamasite** [AgoraIO/Basic-Video-Call#204]
**Describe the bug**
https://github.com/AgoraIO/Basic-Video-Call/tree/master/Group-Video/OpenVideoCall-Linux 里的英文开发环境要求不正确：
![image](https://user-images.githubusercontent.com/10089260/86759852-610b6780-c077-11ea-96d0-7a1f110af55b.png)

应为：

- OS:
  - Ubuntu 12.04 x64 or higher
  - CentOS 7 or higher

- CPU:
  - x86_64

- Compiler:
  - gcc 4.8 or higher

**Comment by plutoless** [comment]
thx. fixed in https://github.com/AgoraIO/Basic-Video-Call/commit/a1f9c8e2146c26890d02ad9668be5a0e1cd7d7a9
