### ISSUE TITLE
One-to-One-Video/Agora-Windows-Tutorial-1to1/README.zh.md 中存在语句重复

### ISSUE THREAD

**Issue by yamasite** [AgoraIO/Basic-Video-Call#207]
**Describe the bug**
https://github.com/AgoraIO/Basic-Video-Call/blob/master/One-to-One-Video/Agora-Windows-Tutorial-1to1/README.zh.md 中存在语句重复：
![image](https://user-images.githubusercontent.com/10089260/87276879-c944c800-c513-11ea-9787-842aabdc7f4b.png)

**Comment by plutoless** [comment]
fixed in https://github.com/AgoraIO/Basic-Video-Call/commit/a4a65d5e58dbcbc822f636b0b7c332335cf9a250
