### ISSUE TITLE
onUserInfoUpdated() call back never called ( Group-Video/ OpenVideoCall-Android )

### ISSUE THREAD

**Issue by saraju2249** [AgoraIO/Basic-Video-Call#208]
### **onUserInfoUpdated() call back never called  After a remote user joins the channel**

**i'm trying to get userInfo by uid and tried the following methods but didn't get any result**

1. I went through official  agora android API Doc and I found one method getUserById and which has two parameter uid and UserInfo (Custom object) and  i tried to call method but i didn't get  callback on the local client , After a remote user joins the channel.

2.  Event tried after onFirstRemoteVideoDecoded but it is returning -113  and UserInfo is still empty   

![image (1)](https://user-images.githubusercontent.com/36325579/87294354-4460ab00-c521-11ea-959f-54680f27c717.png)
![image](https://user-images.githubusercontent.com/36325579/87294377-52163080-c521-11ea-837d-5a54fead6d1e.png)

  Thanks in advance

**Comment by plutoless** [comment]
how do you join the channel? 
will this help? https://github.com/AgoraIO/Advanced-Video/tree/dev/backup/String-Account
