### ISSUE TITLE
Agora web SDK在IOS12手机上使用safari的问题

### ISSUE THREAD

**Issue by tianmaogen** [AgoraIO/Basic-Video-Call#21]
我参照项目 Basic-Video-Call / Group-Video / OpenVideoCall-Web 做了修改，教师用firefox共享桌面和语音，学生用电脑可以看到画面和声音。
但是在IOS12 iPhone6s上使用safari观看存在以下两个问题:

1. 学生只能看到画面，听不到声音。
2. 学生在iPhone6s上使用 safari浏览器调用 SDK的方法 `localStream.init` 方法之后没有回调。
```
localStream = streamInit(uid, options, config);
    // enableDualStream();
    localStream.init(
      () => {
        addStream(localStream, true);
        client.publish(localStream, err => {
          alert('error!'+ err)
          localLog('Publish local stream error: ' + err);
        });
      },
      err => {
        localLog('getUserMedia failed', err);
      }
    );
```
请问是不是Agora web SDK本身不支持手机上使用safari进行互动直播？

* 学生端JS代码:

[meeting2.txt](https://github.com/AgoraIO/Basic-Video-Call/files/2697881/meeting2.txt)

* 教师端JS代码:

[meeting1.txt](https://github.com/AgoraIO/Basic-Video-Call/files/2697879/meeting1.txt)

**Comment by plutoless** [comment]
hi @tianmaogen 
应该是支持的，但由于系统的原因safari本身对使用的要求可能会有一点高，这边能不能先访问https://webdemo.agora.io/videocall/ 尝试一下看是否一切正常？
