### ISSUE TITLE
'streamList' is assigned a value but never used  @typescript-eslint/no-unused-vars

### ISSUE THREAD

**Issue by designerprasan007** [AgoraIO/Basic-Video-Call#212]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Linux]
 - Version [e.g. 83]

**Smartphone (please complete the following information):**

**Additional context**
hi, agora team, you have built such wonderful and very helpful streaming code, this is working absolutely fine before, but now a days I freshly cloned from github https://github.com/AgoraIO/Basic-Video-Call and I want to run https://github.com/AgoraIO/Basic-Video-Call/tree/master/One-to-One-Video/Agora-Web-Tutorial-1to1-React which is built on react, but when I gave command of npm run dave as given in the readme it's throwing error of 

> Compiled with warnings.

./src/App.tsx
  Line 141:  'streamList' is assigned a value but never used  @typescript-eslint/no-unused-vars

./src/hooks/useMediaStream.ts
  Line 82:  React Hook useEffect has a missing dependency: 'remoteStreamList'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

how can I resolve this, and I'm completely new to the React.js so have very minimal knowledge of debugging the react code, thank you advance.

**Comment by plutoless** [comment]
they are just warnings you can ignore if not interested. if you definitely want to fix this these lint warnings have already told you the reason.
