### ISSUE TITLE
Sometimes can not hear other people talk 

### ISSUE THREAD

**Issue by truonglocbinh** [AgoraIO/Basic-Video-Call#213]
When I run https://github.com/AgoraIO/Basic-Video-Call/tree/master/Group-Video/OpenVideoCall-Web for group . I use Iphone Xr with Ios `13.5.1` version, sometimes I can not  listen a other people talk. But when I talk they can hear me talk. So please help me

**Comment by truonglocbinh** [comment]
@plutoless  Can you help me . Is it agora stable for Safari Ios

**Comment by plutoless** [comment]
could you pls provide logs or channels so that i can help? is this 100% reproducible?
