### ISSUE TITLE
How to stop sending the remote audio stream  ( Group-Video/ OpenVideoCall-Android )

### ISSUE THREAD

**Issue by saraju2249** [AgoraIO/Basic-Video-Call#214]
**I have a situation where host need to stop other's remote audio stream**

**Current scenario**

  If i call the muteRemoteAudioStream ( int uid, boolean muted ) method it receive/stop receiving the specified remote user's audio stream

 Example - there are three users (u1, u2, u3) on same room  
 
 when u1 mute to u2 , then u1 stop receiving audio from  u2 but u3 still can hear p2

**But Expected  scenario is little bit different**

i want case like  -  when u1 mute to u2 , then u1 and u3 both should stop receiving audio from u2 

and on A successful muteRemoteAudioStream there should be a call trigger the onUserMuteAudio callback on the remote client.

Is there any way to implement this scenario ?, i saw this function already available on official Agora Video Call App.

**Thanks in advance**

![Screenshot_2020-07-20-16-58-59](https://user-images.githubusercontent.com/36325579/87937558-9457e880-cab2-11ea-820a-5bd2f9b1fc9f.png)

**Comment by plutoless** [comment]
@saraju2249 in this case, you will need to use some kind of signaling system to notify the client, the remote client receive the notification and call mute local on his end. Agora RTM sdk is a good option, while you can also setup a websocket server yourself to redirect the message.
