### ISSUE TITLE
How to mute remotestream users ( Group-Video/ OpenVideoCall)  Web app SDK

### ISSUE THREAD

**Issue by kumargowdaa** [AgoraIO/Basic-Video-Call#215]
I have a situation where host need to stop other's remote audio stream

Current scenario

If i call the muteRemoteAudioStream ( int uid, boolean muted ) method it receive/stop receiving the specified remote user's audio stream

Example - there are three users (u1, u2, u3) on same room

when u1 mute to u2 , then u1 stop receiving audio from u2 but u3 still can hear p2

But Expected scenario is little bit different

i want case like - when u1 mute to u2 , then u1 and u3 both should stop receiving audio from u2

and on A successful muteRemoteAudioStream there should be a call trigger the onUserMuteAudio callback on the remote client.

Is there any way to implement this scenario ?, i saw this function already available on official Agora web App.

Thanks in advance

**Comment by plutoless** [comment]
sounds like a very similar question to https://github.com/AgoraIO/Basic-Video-Call/issues/214
