### ISSUE TITLE
One-to-One-Video/Agora-macOS-Tutorial-Objective-C-1to1/README.zh.md 内容过时

### ISSUE THREAD

**Issue by yamasite** [AgoraIO/Basic-Video-Call#217]
**Describe the bug**

中英文都需要更新:

> Download the Agora Video SDK. Unzip the downloaded SDK package and copy the following files from the SDK libs folder into the sample application Agora Mac Tutorial Swift folder.
> 
> - AograRtcEngineKit.framework
> - AgoraRtcCryptoLoader.framework
> - libcrypto.a

现在最新的 macOS Video SDK 包并没有这三个文件,而是合成了一个:

![image](https://user-images.githubusercontent.com/10089260/88138778-edde2580-cc20-11ea-9081-2d0132bef8bc.png)

**Comment by yamasite** [comment]
One-to-One-Video/Agora-macOS-Tutorial-Swift-1to1 的 readme 也有这个问题

**Comment by plutoless** [comment]
感觉提醒 我会尽快更新下
