### ISSUE TITLE
Group-Video/OpenVideoCall-Linux readme 未说明去哪里拿  libagora_rtc_sdk.so

### ISSUE THREAD

**Issue by yamasite** [AgoraIO/Basic-Video-Call#218]
**Describe the bug**

> 运行示例程序
> 首先在 Agora.io 注册 注册账号，并创建自己的测试项目，获取到 AppID。将 AppID 填写进 run.sh
> 
> --appId "your app ID"
> 然后在 Agora.io SDK 下载 视频通话 + 直播 SDK，解压后将其中libs文件夹下的
> 
> libagora_rtc_sdk.so

这个 libagora_rtc_sdk.so 是从哪里得来的?下载哪个平台的 SDK呢?

**Comment by plutoless** [comment]
linux平台的sdk目前没有产品化，您如果有强需求可以联系销售获取哈
