### ISSUE TITLE
chrome.window.webstore is undefined

### ISSUE THREAD

**Issue by VivekNair** [AgoraIO/Basic-Video-Call#22]
Hey team,

In `src/utils/BrowserCheck.js` within the OpenVideoCall-Web sub-repository, `window.chrome.webstore` is undefined. [According to this StackOverflow post ](https://stackoverflow.com/questions/81099/safe-feature-based-way-for-detecting-google-chrome-with-javascript), Chrome 71 released on December 4th made this undefined.

Best,
Vivek

**Comment by menthays** [comment]
Thanks for your attention , we have update related logic in https://github.com/AgoraIO/Basic-Video-Call/commit/c6eae9c2dbd1d1274968d7ef7b09e0c5d6867309
