### ISSUE TITLE
Agora-iOS-Tutorial-SwiftUI-1toMany

### ISSUE THREAD

**Issue by hasanals** [AgoraIO/Basic-Video-Call#220]
Hello, 
I'm trying to integrate Agora to my swiftui app, but was not able to create a 1 to many video call. I'm trying to make something similar to Instagram Live. till now I had no luck of showing the Admin video on the viewers screens. 
Can you please lead me to the right direction.

Thanks,

**Comment by yoreland** [comment]
If you just want to get some reference regarding show agora video canvas in swift ui, you could check the swiftUI demo 1v1: https://github.com/AgoraIO/Basic-Video-Call/tree/master/One-to-One-Video/Agora-iOS-Tutorial-SwiftUI-1to1
If you have other specific issues, can you upload more details, like logs or screenshot?

**Comment by hasanals** [comment]
I tried the tutorial you provided, I wasn't able to stream the video as audience. please check the following link for the code I used.
https://stackoverflow.com/questions/63164334/agora-swiftui-openlive-integration-issues#comment111695510_63164334

I also tried implementing storyboard into swiftui using the following tutorial and it didn't work as well for the audience role. I wasn't able to preview the video stream I was only able to listen to the sound of the broadcaster but not the video.
https://github.com/AgoraIO/Basic-Video-Broadcasting/tree/master/OpenLive-iOS

**Comment by plutoless** [comment]
@hasanals in the SO page you posted clearly you are not hooking up remote video properly as the post reply indicates. could you pls double check that? i see you have call setupLocalVideo to set up local video canvas, and that's why broadcast role works for you as what you see if local preview.
