### ISSUE TITLE
Heroku build issues

### ISSUE THREAD

**Issue by kirkglodf** [AgoraIO/Basic-Video-Call#222]
**Describe the bug**
I forked the code for group call for web. It runs on my laptop without a hitch. When i deploy to heroku with a react build pack the build succeeded, however, when i go to the url it shows 404. What am i missing?

Error:
404 Not Found
nginx

**Comment by plutoless** [comment]
404 usually means it failed to find the html file. i have no idea how you deploy to heroku so i'm afraid that i can hardly help here.

**Comment by kirkglodf** [comment]
@plutoless Thanks for responding. I figured out the issue.
