### ISSUE TITLE
Not able to start video call

### ISSUE THREAD

**Issue by Sushant-Hande** [AgoraIO/Basic-Video-Call#225]
I have set up the https://github.com/AgoraIO/Basic-Video-Call#1-to-1-video-calls sample. The app is running on device but I am not getting how to initiate the call with other users?

**Comment by plutoless** [comment]
you will need to ask others to join to the same channel with you. then you should be able to see each other.

**Comment by plutoless** [comment]
if you need a more comprehensive call example, please take a look at here.
https://github.com/AgoraIO-Usecase/Video-Calling

**Comment by Sushant-Hande** [comment]
Thank you, @plutoless. I will look into it.
