### ISSUE TITLE
No implementation found for method launch on channel

### ISSUE THREAD

**Issue by chengbieSWL** [AgoraIO/Basic-Video-Call#227]
Android黑屏
其他扑通通道
该io.flutter.embedding.android.FlutterActivity会由注册的所有插件的自动configureFlutterEngine方法

别忘了加 super.configureFlutterEngine(flutterEngine)
不要加 GeneratedPluginRegistrant.registerWith(flutterEngine)

我用这个方法解决问题后，导致其他插件
No implementation found for method launch on channel
请问怎么办

**Comment by LichKing-2234** [comment]
最新的dev版本已经兼容了多次注册插件的情况，而且flutter官方应该也修复了这个问题，最新的不会注册两次
