### ISSUE TITLE
Both local and remote video call display black screen but audio works fine

### ISSUE THREAD

**Issue by chuksdsilent** [AgoraIO/Basic-Video-Call#228]
I run the app my phone and the remote device but both are showing black screen. 

How do I fix this error. I have done what has been stated on agora docs concerning this issue but my problem has persisted.

public class VideoChatViewActivity extends AppCompatActivity {
private static final String TAG = VideoChatViewActivity.class.getSimpleName();

private static final int PERMISSION_REQ_ID = 22;

private static final String[] REQUESTED_PERMISSIONS = {
        Manifest.permission.RECORD_AUDIO,
        Manifest.permission.CAMERA,
        Manifest.permission.WRITE_EXTERNAL_STORAGE
};

private RtcEngine mRtcEngine;
private boolean mCallEnd;
private boolean mMuted;

private FrameLayout mLocalContainer;
private RelativeLayout mRemoteContainer;
private SurfaceView mLocalView;
private SurfaceView mRemoteView;

private ImageView mCallBtn;
private ImageView mMuteBtn;
private ImageView mSwitchCameraBtn;

// Customized logger view
private LoggerRecyclerView mLogView;

    @Override
    public void onJoinChannelSuccess(String channel, final int uid, int elapsed) {
        runOnUiThread(new Runnable() {
            @Override
            public void run() {
                mLogView.logI("Join channel success, uid: " + (uid & 0xFFFFFFFFL));
            }
        });
    }

    
    @Override
    public void onFirstRemoteVideoDecoded(final int uid, int width, int height, int elapsed) {
        runOnUiThread(new Runnable() {
            @Override
            public void run() {
                mLogView.logI("First remote video decoded, uid: " + (uid & 0xFFFFFFFFL));
                setupRemoteVideo(uid);
            }
        });
    }

    @Override
    public void onUserOffline(final int uid, int reason) {
        runOnUiThread(new Runnable() {
            @Override
            public void run() {
                mLogView.logI("User offline, uid: " + (uid & 0xFFFFFFFFL));
                onRemoteUserLeft();
            }
        });
    }
};

private void setupRemoteVideo(int uid) {
    int count = mRemoteContainer.getChildCount();
    View view = null;
    for (int i = 0; i < count; i++) {
        View v = mRemoteContainer.getChildAt(i);
        if (v.getTag() instanceof Integer && ((int) v.getTag()) == uid) {
            view = v;
        }
    }

    if (view != null) {
        return;
    }

   
    mRemoteView = RtcEngine.CreateRendererView(getBaseContext());
    mRemoteContainer.addView(mRemoteView);
    // Initializes the video view of a remote user.
    mRtcEngine.setupRemoteVideo(new VideoCanvas(mRemoteView, VideoCanvas.RENDER_MODE_HIDDEN, uid));
    mRemoteView.setTag(uid);
}

private void onRemoteUserLeft() {
    removeRemoteVideo();
}

private void removeRemoteVideo() {
    if (mRemoteView != null) {
        mRemoteContainer.removeView(mRemoteView);
    }
    // Destroys remote view
    mRemoteView = null;
}

@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_video_chat_view);
    initUI();

    // Ask for permissions at runtime.
    // This is just an example set of permissions. Other permissions
    // may be needed, and please refer to our online documents.
    if (checkSelfPermission(REQUESTED_PERMISSIONS[0], PERMISSION_REQ_ID) &&
            checkSelfPermission(REQUESTED_PERMISSIONS[1], PERMISSION_REQ_ID) &&
            checkSelfPermission(REQUESTED_PERMISSIONS[2], PERMISSION_REQ_ID)) {
        initEngineAndJoinChannel();
    }
}

private void initUI() {
    mLocalContainer = findViewById(R.id.local_video_view_container);
    mRemoteContainer = findViewById(R.id.remote_video_view_container);

    mCallBtn = findViewById(R.id.btn_call);
    mMuteBtn = findViewById(R.id.btn_mute);
    mSwitchCameraBtn = findViewById(R.id.btn_switch_camera);

    mLogView = findViewById(R.id.log_recycler_view);

    // Sample logs are optional.
    showSampleLogs();
}

private void showSampleLogs() {
    mLogView.logI("Welcome to Agora 1v1 video call");
    mLogView.logW("You will see custom logs here");
    mLogView.logE("You can also use this to show errors");
}

private boolean checkSelfPermission(String permission, int requestCode) {
    if (ContextCompat.checkSelfPermission(this, permission) !=
            PackageManager.PERMISSION_GRANTED) {
        ActivityCompat.requestPermissions(this, REQUESTED_PERMISSIONS, requestCode);
        return false;
    }
    return true;
}

@Override
public void onRequestPermissionsResult(int requestCode,
                                       @NonNull String[] permissions, @NonNull int[] grantResults) {

    if (requestCode == PERMISSION_REQ_ID) {
        if (grantResults[0] != PackageManager.PERMISSION_GRANTED ||
                grantResults[1] != PackageManager.PERMISSION_GRANTED ||
                grantResults[2] != PackageManager.PERMISSION_GRANTED) {
            showLongToast("Need permissions " + Manifest.permission.RECORD_AUDIO +
                    "/" + Manifest.permission.CAMERA + "/" + Manifest.permission.WRITE_EXTERNAL_STORAGE);
            finish();
            return;
        }

        // Here we continue only if all permissions are granted.
        // The permissions can also be granted in the system settings manually.
        initEngineAndJoinChannel();
    }
}

private void showLongToast(final String msg) {
    this.runOnUiThread(new Runnable() {
        @Override
        public void run() {
            Toast.makeText(getApplicationContext(), msg, Toast.LENGTH_LONG).show();
        }
    });
}

private void initEngineAndJoinChannel() {
    // This is our usual steps for joining
    // a channel and starting a call.
    initializeEngine();
    setupVideoConfig();
    setupLocalVideo();
    joinChannel();
}

private void initializeEngine() {
    try {
        mRtcEngine = RtcEngine.create(getBaseContext(), getString(R.string.agora_app_id), mRtcEventHandler);
    } catch (Exception e) {
        Log.e(TAG, Log.getStackTraceString(e));
        throw new RuntimeException("NEED TO check rtc sdk init fatal error\n" + Log.getStackTraceString(e));
    }
}

private void setupVideoConfig() {
    // In simple use cases, we only need to enable video capturing
    // and rendering once at the initialization step.
    // Note: audio recording and playing is enabled by default.
    mRtcEngine.enableVideo();

    // Please go to this page for detailed explanation
    // https://docs.agora.io/en/Video/API%20Reference/java/classio_1_1agora_1_1rtc_1_1_rtc_engine.html#af5f4de754e2c1f493096641c5c5c1d8f
    mRtcEngine.setVideoEncoderConfiguration(new VideoEncoderConfiguration(
            VideoEncoderConfiguration.VD_640x360,
            VideoEncoderConfiguration.FRAME_RATE.FRAME_RATE_FPS_15,
            VideoEncoderConfiguration.STANDARD_BITRATE,
            VideoEncoderConfiguration.ORIENTATION_MODE.ORIENTATION_MODE_FIXED_PORTRAIT));
}

private void setupLocalVideo() {
    
    mRtcEngine.setupLocalVideo(new VideoCanvas(mLocalView, VideoCanvas.RENDER_MODE_HIDDEN, 0));
}

private void joinChannel() {
    String token = getString(R.string.agora_access_token);
    if (TextUtils.isEmpty(token) || TextUtils.equals(token, "#YOUR ACCESS TOKEN#")) {
        token = null; // default, no token
    }
    mRtcEngine.joinChannel(token, "demoChannel1", "Extra Optional Data", 0);
}

@Override
protected void onDestroy() {
    super.onDestroy();
    if (!mCallEnd) {
        leaveChannel();
    }
    /*
      Destroys the RtcEngine instance and releases all resources used by the Agora SDK.

      This method is useful for apps that occasionally make voice or video calls,
      to free up resources for other operations when not making calls.
     */
    RtcEngine.destroy();
}

private void leaveChannel() {
    mRtcEngine.leaveChannel();
}

public void onLocalAudioMuteClicked(View view) {
    mMuted = !mMuted;
    // Stops/Resumes sending the local audio stream.
    mRtcEngine.muteLocalAudioStream(mMuted);
    int res = mMuted ? R.drawable.btn_mute : R.drawable.btn_unmute;
    mMuteBtn.setImageResource(res);
}

public void onSwitchCameraClicked(View view) {
    // Switches between front and rear cameras.
    mRtcEngine.switchCamera();
}

public void onCallClicked(View view) {
    if (mCallEnd) {
        startCall();
        mCallEnd = false;
        mCallBtn.setImageResource(R.drawable.btn_endcall);
    } else {
        endCall();
        mCallEnd = true;
        mCallBtn.setImageResource(R.drawable.btn_startcall);
    }

    showButtons(!mCallEnd);
}

private void startCall() {
    setupLocalVideo();
    joinChannel();
}

private void endCall() {
    removeLocalVideo();
    removeRemoteVideo();
    leaveChannel();
}

private void removeLocalVideo() {
    if (mLocalView != null) {
        mLocalContainer.removeView(mLocalView);
    }
    mLocalView = null;
}

private void showButtons(boolean show) {
    int visibility = show ? View.VISIBLE : View.GONE;
    mMuteBtn.setVisibility(visibility);
    mSwitchCameraBtn.setVisibility(visibility);
}

**Comment by plutoless** [comment]
have you changed anything to the original code? Have you granted access to the camera? how can i reproduce your issue? Could you pls help guide me the stelps?

**Comment by colorgold** [comment]
> have you changed anything to the original code? Have you granted access to the camera? how can i reproduce your issue? Could you pls help guide me the steps?

I am also facing the same issue. It was working fine until today and only the audio is heard. Does the audience need to grant access to the camera if they will not be going live themselves? These are the steps I took:

1. Agora is initialized as soon as the user starts the live video activity
```
try {
            rtcEngine = RtcEngine.create(this, getString(R.string.agora_app_id), rtcEngineEventHandler);
            rtcEngine.setChannelProfile(Constants.CHANNEL_PROFILE_LIVE_BROADCASTING);
            rtcEngine.enableVideo();
            rtcEngine.enableAudio();
    } catch (Exception e) {
            rtcEngine = null;
    }
```
My rtcEngineEventHandler is as follows:
```
private final IRtcEngineEventHandler rtcEngineEventHandler = new IRtcEngineEventHandler() {
        @Override
        public void onJoinChannelSuccess(final String channel, final int uid, int elapsed) {
            super.onJoinChannelSuccess(channel, uid, elapsed);
            runOnUiThread(new Runnable() {
                @Override
                public void run() {
                    Toast.makeText(ChatRadioActivities.this, getString(R.string.channel_joined, radioName), Toast.LENGTH_SHORT).show();
                    //Log.d(TAG, "agora: onJoinChannelSuccess: success " + channel + ":user:" + uid);
                }
            });

        }

      
        @Override
        public void onError(final int i) {
            super.onError(i);
            runOnUiThread(new Runnable() {
                @Override
                public void run() {
                    Log.d(TAG, "agora: onError: " + i);
                }
            });

        }

        @Override
        public void onFirstRemoteVideoFrame(int uid, int width, int height, int elapsed) {
            super.onFirstRemoteVideoFrame(uid, width, height, elapsed);

        }

        @Override
        public void onRemoteVideoStateChanged(final int uid, int state, int reason, int elapsed) {
            super.onRemoteVideoStateChanged(uid, state, reason, elapsed);

            //Use REMOTE_VIDEO_STATE_STARTING(1) or REMOTE_VIDEO_STATE_DECODING(2)
            if (state == Constants.REMOTE_VIDEO_STATE_STARTING) {
                //setup remote video
                runOnUiThread(new Runnable() {
                    @Override
                    public void run() {
                        Log.d(TAG, "agora: onRemoteVideoStateChanged: uid: " + uid);
                        initRemoteVideo(uid);
                    }
                });
            }
        }
    };
```
2. The user joins this channel "radio1" as an example when they click the "Join" button.
```
private void joinChannel() {
        setClientRole(Constants.CLIENT_ROLE_AUDIENCE);
        rtcEngine.joinChannel(null, radioId, userID, 0);
}
```
3. the handler events show that user joined the channel successfully and `onRemoteVideoStateChanged`  initializes the remote video like this:

```
SurfaceView surfaceView = RtcEngine.CreateRendererView(this);
        remoteVideoList.add(surfaceView);
        remoteVideoKeyList.add(uid);
        rlRemoteVideos.addView(surfaceView);
        rtcEngine.setupRemoteVideo(new VideoCanvas(surfaceView, VideoCanvas.RENDER_MODE_FILL, uid, Constants.VIDEO_MIRROR_MODE_AUTO));
        rtcEngine.muteRemoteVideoStream(uid,true);
```
I have tried changing the VideoCanvas to `VideoCanvas.RENDER_MODE_FIT` and `VideoCanvas.RENDER_MODE_HIDDEN`
but same results are given (only audio but no video).

I was wondering which state in `onRemoteVideoStateChanged` is best to initialize the video. Or, should I be using `onFirstRemoteVideoFrame` instead?

**Comment by plutoless** [comment]
hi sorry for late reply. i tried searching "radio1" as the channel name but failed to find any sessions. Are you sure you are joining this channel? i see you have a variable radioId but i can't see its actual value.
also if you can hear opposite audio, but can't see opposite's video. there's a high chance the broadcaster is not sending video. If you can share the precise channel name you used i can try searching from backend.

**Comment by colorgold** [comment]
@plutoless Thank you for the reply. The actual channel name is: `-LUqTEpEVRJRaF5KRv_3`
On the web, it shows up fine. However, when I try to watch it on my phone it does not show.

**Comment by colorgold** [comment]
I am using version `AgoraRTCSDK-3.2.1.js` which is where I am going live from. And, I am using `io.agora.rtc:full-sdk:3.1.2` on Android to watch the video. I am able to go live and watch the video just fine on my computer. However, I am unable to do so from the app on my phone. On the phone, the surfaceview freezes on the first image it receives. Other times it just shows a black screen.

**Comment by plutoless** [comment]
@colorgold hi i checked the backend. it seems you are muting remote video on android device when remote joins.
which refers to this api rtcEngine.muteRemoteVideoStream(uid,true);
if you mute remote video stream you will not be able to receive the video stream

**Comment by plutoless** [comment]
also from the backend i'm seeing you muting your local video soon after you mute remote video stream. have you made any changes to our original demo?

**Comment by plutoless** [comment]
also from the backend i'm seeing you muting your local video soon after you mute remote video stream. have you made any changes to our original demo?

**Comment by colorgold** [comment]
@plutoless Oh my goodness sakes. You're right. I muted the video instead of muting the audio in `onFirstRemoteVideoFrame`.  I was trying to allow the audience to mute and unmute the audio. I have fixed this and I am now able to see the video. Thanks!
