### ISSUE TITLE
Not able to view the Web and Android video call

### ISSUE THREAD

**Issue by ShanavazJs** [AgoraIO/Basic-Video-Call#236]
I have executed the Group video call (Web) sample project and i can able to view the ios peer video and another web peer video but unable to view the android's peer video. It shows the black screen in both side (web and android)

**Comment by yoreland** [comment]
Hello, I am just verifying the same but it seems works fine.
Regarding the issue, you mentioned "black screen in both side"
Do you mean android side also see black screen for local video or black screen for web side?

**Comment by ShanavazJs** [comment]
@yoreland  Both the side we are getting black screen. Android and web side as well.
Please let me know which version of mobile you are used to test. 
We are testing from Android 9 version.

**Comment by yoreland** [comment]
@ShanavazJs 
Sorry for late response we are just back from public holiday.
The testing device I am using is Samsung s8+ android 8.
Do you have channel name for reproduce the issue? We could have a check from back end console.

**Comment by androidparth90** [comment]
Can this issue be re-opened again?  I am facing the same thing
