### ISSUE TITLE
How to enable to the annotation response from android or ios to Web

### ISSUE THREAD

**Issue by ShanavazJs** [AgoraIO/Basic-Video-Call#237]
When we added some annotation from ios, android while video streaming the same has to be show on web side as well,
Please let us know how to enable that.

eg  : 
From android if i streaming a bike, and i want to draw one circle on my screen to bike part to denote some issue on the bike with help of AR Kit , the same needs to show to the web application.

**Comment by yoreland** [comment]
One of solutions could be sharing the screen of app. Here it is some guide line about iOS/android screen sharing:
https://docs.agora.io/en/Interactive%20Broadcast/screensharing_android?platform=Android
