### ISSUE TITLE
PIP mode

### ISSUE THREAD

**Issue by Komal2905** [AgoraIO/Basic-Video-Call#238]
does Agora SDK provide PIP mode for iOS?

**Comment by yoreland** [comment]
current PIP feature in iOS 14 is basically based on AVPlayer or AVPlayerLayer. There seems no way to generate the AVAsset objects using an external source, only getting the source via URLs to web-based or file-based sources. 
Please kindly let us know if other RTC provider only PIP here. We are glad to follow up and research how to do the same.

**Comment by softsan** [comment]
@yoreland  any direction on this or related docs?

**Comment by plutoless** [comment]
@softsan as commented this is currently not supported.
