### ISSUE TITLE
Volume problem on Android 9 (Pie)

### ISSUE THREAD

**Issue by SerhiiSolobaievUptech** [AgoraIO/Basic-Video-Call#24]
Everything works correctly on Android < 9, but on the Pie we have a problem: volume doesn't change at all. Even in `Do not disturb` mode sounds still playing.

Agora version: 2.3.0, devices: all phones with Android Pie

**Comment by plutoless** [comment]
@guohai

**Comment by SerhiiSolobaievUptech** [comment]
Seems that it is fixed in v2.3.2
Can be closed)
