### ISSUE TITLE
The Windows QT example does not work with v3.1.2

### ISSUE THREAD

**Issue by yamasite** [AgoraIO/Basic-Video-Call#242]
**Describe the bug**
The [Windows QT example](https://github.com/AgoraIO/Basic-Video-Call/tree/master/Group-Video/OpenVideoCall-Windows) in the master branch does not work with v3.1.2 SDK and reports the following errors:

![image](https://user-images.githubusercontent.com/10089260/97139419-6959f080-1795-11eb-913f-4a5f4c6abb86.png)

**Additional context**
After switching to dev/3.1.0 or later, the error disappeared. Please update the master branch at your earliest convenience. Otherwise, the new SDK may not work with this demo.

**Comment by CLuCheng** [comment]
Thank you for reminding us that we are merging into the main branch.

**Comment by plutoless** [comment]
https://github.com/AgoraIO/Basic-Video-Call/pull/231
