### ISSUE TITLE
node-sass installation failed

### ISSUE THREAD

**Issue by palakvc** [AgoraIO/Basic-Video-Call#247]
**Describe the bug**
Getting issue with installation on the basic video call web

**To Reproduce**
1. Go to 'Basic-Video-Call\Group-Video\OpenVideoCall-Web>'
2. npm install

**Screenshots**
![image](https://user-images.githubusercontent.com/42599914/99376813-72009b00-28eb-11eb-9d5f-53fb8d2d5873.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome
 - Node v15.2.0
- npm v7.0.8

**Comment by yoreland** [comment]
From log trace. It complains on python environment.
Do you have python installed on your machine?

**Comment by Palaklive** [comment]
@yoreland I have done the review issue cause to the Node updated version 15> I just back Node v12.x.x everything working fine.

**Comment by plutoless** [comment]
thanks.
