### ISSUE TITLE
Stream from Android video call not getting displayed on Web 

### ISSUE THREAD

**Issue by androidparth90** [AgoraIO/Basic-Video-Call#261]
**Describe the bug**
Stream sent from Android video call not visible on web

**To Reproduce**
1. Use the Android Video Call 1 to 1 demo. Just use the Streamer functionality to stream the video
2. Use the Web Video Call 1 to 1 demo, just use the remote video view to display stream coming from Android

**Expected behavior**
Stream from Android should be visible on web

**Desktop:**
 - OS: - MacOSX Catalina
 - Browser - Chrome
 - Version - Latest

**Smartphone**
 - Device: [Samsung A30]
 - OS: [Android]
 - Version [10]

**Comment by plutoless** [comment]
@androidparth90  would you help provide the channel name and time when the issue happened so that we can check from our backend? cheers

**Comment by androidparth90** [comment]
hi channel name is test_channel

**Comment by androidparth90** [comment]
@plutoless : Can you please help ?

**Comment by plutoless** [comment]
i tried searching AgoraARStreamerActivity but failed. are you sure it's from this repository?
i checked your channel from backend, it seems web does not join the channel successfully.

**Comment by androidparth90** [comment]
Hi @plutoless: thanks for your reply 
The Android demo app is taken from here : https://github.com/AgoraIO-Community/ARCoreAgora
I have referred this link: https://www.agora.io/en/blog/build-an-augmented-reality-remote-assistance-app-in-android/

The web demo app is taken from here: https://github.com/AgoraIO/Basic-Video-Call/tree/master/One-to-One-Video/Agora-Web-Tutorial-1to1

Ok what is the error seen on the web. Can you please provide some description because I do not any errors in the console for web

**Comment by plutoless** [comment]
@androidparth90 umm i just don't see any user session with web platform in the channel you mentioned. but i do see iOS is in there.

**Comment by androidparth90** [comment]
ohh thats strange. Basically do you have a sample or solution that can stream video from Android to web, that would be helpful for me. As seen in the exmample link I provided, I need to do 1-1 video call from Android to web.

**Comment by plutoless** [comment]
@androidparth90 i double checked all your call history and none of them has web. could you pls copy paste your web console logs?

**Comment by androidparth90** [comment]
Ok sure. I will post the complete logs in some time

**Comment by androidparth90** [comment]
Apologies for the delay in reply, here are the web logs from the developer console @plutoless 

21:25:33:837 Agora-SDK [DEBUG]: >>> add event listener >>>>
AgoraRTCSDK.min.js:2 21:25:33:839 Agora-SDK [DEBUG]: Object isAPISupport: true, isVendorAndVersionSupport: true
(index):123 agora sdk version: 3.4.0 compatible: true
AgoraRTCSDK.min.js:2 21:29:06:198 Agora-SDK [DEBUG]: AudioContext is suspended, auto resume
AgoraRTCSDK.min.js:2 21:29:06:219 Agora-SDK [DEBUG]: AudioContext resume success
(index):557 join
AgoraRTCSDK.min.js:2 21:29:20:274 Agora-SDK [INFO]: Creating client, MODE: live CODEC: h264
AgoraRTCSDK.min.js:2 21:29:20:281 Agora-SDK [INFO]: [EFA71] Adding event handler on error
(index):383 init success
AgoraRTCSDK.min.js:2 21:29:20:287 Agora-SDK [INFO]: processId: process-686b3cd6-d42f-47da-ae2e-a0ce291b4979
AgoraRTCSDK.min.js:2 21:29:20:288 Agora-SDK [DEBUG]: Flush cached event reporting: 3
AgoraRTCSDK.min.js:2 21:29:20:290 Agora-SDK [DEBUG]: [EFA71] Connect to choose_server: https://webrtc2-ap-web-1.agora.io/api/v1, GLOBAL
AgoraRTCSDK.min.js:2 21:29:20:295 Agora-SDK [DEBUG]: [EFA71] Connect to choose_server: https://webrtc2-ap-web-2.agoraio.cn/api/v1, CN
AgoraRTCSDK.min.js:2 21:29:20:299 Agora-SDK [INFO]: [EFA71] Added event handler on error, peer-leave, stream-published, stream-added, stream-subscribed, stream-removed, onTokenPrivilegeWillExpire, onTokenPrivilegeDidExpire
AgoraRTCSDK.min.js:2 21:29:20:487 Agora-SDK [INFO]: [EFA71] Joining channel: test_channel
AgoraRTCSDK.min.js:2 21:29:20:489 Agora-SDK [DEBUG]: [EFA71] register client Channel test_channel Uid 698672714
AgoraRTCSDK.min.js:2 21:29:20:595 Agora-SDK [DEBUG]: [EFA71] Connected to gateway server
AgoraRTCSDK.min.js:2 21:29:20:605 Agora-SDK [INFO]: [EFA71] Join channel test_channel success, join with uid: 698672714.
(index):407 join channel: test_channel success, uid: 698672714
AgoraRTCSDK.min.js:2 21:29:20:621 Agora-SDK [DEBUG]: Create stream
AgoraRTCSDK.min.js:2 21:29:20:626 Agora-SDK [DEBUG]: [698672714] Requested access to local media
AgoraRTCSDK.min.js:2 21:29:20:627 Agora-SDK [DEBUG]: GetUserMedia {"video":{"deviceId":{"exact":"ab4812ad209fa2e9b05da751f1d3a1c4e39207f4895bee252cacbff4357d1d8b"},"width":640,"height":480,"frameRate":15},"audio":{"deviceId":{"exact":"default"}}}
AgoraRTCSDK.min.js:2 21:29:20:687 Agora-SDK [INFO]: [EFA71] Newly added remote stream with uid 1583410515.
AgoraRTCSDK.min.js:2 21:29:20:691 Agora-SDK [INFO]: [EFA71] Gatewayclient 698672714 Subscribe 1583410515: {"video":true,"audio":true}
AgoraRTCSDK.min.js:2 {nop2p: true, audio: true, video: true, screen: false, callback: ƒ, …}
(index):310 stream-added remote-uid:  1583410515
AgoraRTCSDK.min.js:2 21:29:20:925 Agora-SDK [INFO]: [EFA71] Remote stream subscribed with uid  1583410515
AgoraRTCSDK.min.js:2 21:29:20:928 Agora-SDK [DEBUG]: [1583410515] play(). remote_video_1583410515 undefined
(index):320 stream-subscribed remote-uid:  1583410515
AgoraRTCSDK.min.js:2 21:29:20:975 Agora-SDK [DEBUG]: [EFA71] subscribe p2p connected:  Map(1) {12800 => {…}}
AgoraRTCSDK.min.js:2 21:29:20:980 Agora-SDK [DEBUG]: Flush cached event reporting: 3
AgoraRTCSDK.min.js:2 21:29:20:985 Agora-SDK [DEBUG]: [EFA71]: use _adjustPCMuteStatus: 1583410515
AgoraRTCSDK.min.js:2 21:29:20:985 Agora-SDK [DEBUG]: [EFA71]: set receiver audio track: true
AgoraRTCSDK.min.js:2 21:29:20:986 Agora-SDK [DEBUG]: [EFA71]: set receiver video track: true
AgoraRTCSDK.min.js:2 21:29:21:547 Agora-SDK [DEBUG]: [698672714] User has granted access to local media
AgoraRTCSDK.min.js:2 21:29:21:549 Agora-SDK [DEBUG]: start vsResHack MediaStream {id: "xiHKDjAQAzj7wLRzpJqX7jP9eIFE2ffzBc8G", active: true, onaddtrack: null, onremovetrack: null, onactive: null, …}
(index):424 init local stream success
AgoraRTCSDK.min.js:2 21:29:21:555 Agora-SDK [INFO]: [EFA71] Publishing stream, uid 698672714
AgoraRTCSDK.min.js:2 21:29:21:556 Agora-SDK [DEBUG]: [EFA71] setClientRole to host
AgoraRTCSDK.min.js:2 {audio: true, video: true, screen: false, optimizationMode: undefined, callback: ƒ, …}
AgoraRTCSDK.min.js:2 21:29:21:603 Agora-SDK [DEBUG]: [EFA71] PeerConnection add stream : MediaStream {id: "xiHKDjAQAzj7wLRzpJqX7jP9eIFE2ffzBc8G", active: true, onaddtrack: null, onremovetrack: null, onactive: null, …}
AgoraRTCSDK.min.js:2 21:29:21:662 Agora-SDK [INFO]: [EFA71] Local stream published with uid 698672714
AgoraRTCSDK.min.js:2 21:29:21:669 Agora-SDK [DEBUG]: [EFA71]Set Video Bitrate - min:100 max:500
AgoraRTCSDK.min.js:2 21:29:21:771 Agora-SDK [DEBUG]: [EFA71] publish p2p connected:  Map(2) {12800 => {…}, 12801 => {…}}
AgoraRTCSDK.min.js:2 21:29:21:773 Agora-SDK [DEBUG]: Flush cached event reporting: 2
AgoraRTCSDK.min.js:2 21:29:21:775 Agora-SDK [INFO]: [EFA71] Publish success, uid: 698672714
(index):298 stream-published
AgoraRTCSDK.min.js:2 21:29:22:604 Agora-SDK [DEBUG]: [EFA71]: Period fir change to: false
AgoraRTCSDK.min.js:2 21:29:23:45 Agora-SDK [DEBUG]: [1583410515] Media Player Status Change {type: "player-status-change", playerId: 0, mediaType: "audio", status: "play", reason: "playing", …}
AgoraRTCSDK.min.js:2 21:29:23:64 Agora-SDK [DEBUG]: [vsResHack] get stream resolution:  640 x 480 MediaStream {id: "xiHKDjAQAzj7wLRzpJqX7jP9eIFE2ffzBc8G", active: true, onaddtrack: null, onremovetrack: null, onactive: null, …}

**Comment by androidparth90** [comment]
![image](https://user-images.githubusercontent.com/6248876/109523606-8ac94100-7ad5-11eb-9cfd-a639bd24ab60.png)

**Comment by plutoless** [comment]
@androidparth90  just notice you are using 2.9.x android sdk. for this version you will need to call enableWebSdkInteroperability

**Comment by androidparth90** [comment]
@plutoless : thanks! where do I need to call this please? can you tell me exactly please considering the sample I am using for Agora Android

**Comment by plutoless** [comment]
@androidparth90 that repo is a community one and out dated. for latest sdk you don't need to call this api. but for 2.9.x you still need to, you will need to set to true yes. this is mandatory for web-native interop

**Comment by androidparth90** [comment]
@plutoless Ok agreed. I will use the latest only. I just need two inputs from you

1. Where can I find the link for latest Android 1-1 Video Call sample using latest SDK ?
2. Assuming I want to check with 2.9.x just for now, where do I need to add this enableWebSdkInteroperability

I am new to Android etc. Please help

**Comment by plutoless** [comment]
1. https://github.com/AgoraIO/Basic-Video-Call/tree/master/One-to-One-Video/Agora-Android-Tutorial-1to1
2. before joinChannel

**Comment by androidparth90** [comment]
ok great..am closing this issue then.
