### ISSUE TITLE
android code

### ISSUE THREAD

**Issue by gaganAriel** [AgoraIO/Basic-Video-Call#27]
please provide link for download only android code

**Comment by plutoless** [comment]
hi @gaganAriel, you can clone or download the code, via github

**Comment by gaganAriel** [comment]
please let me know how two users connect each other for video call

**Comment by gaganAriel** [comment]
mean two users join a channel?

**Comment by gaganAriel** [comment]
i'm working on one to one video chat

**Comment by plutoless** [comment]
https://github.com/AgoraIO/Basic-Video-Call/tree/master/One-to-One-Video/Agora-Android-Tutorial-1to1
It’s all in here

**Comment by gaganAriel** [comment]
mRtcEngine.joinChannel(null, "demoChannel2", "Extra Optional Data", 0); // if you do not specify the uid,



why token is null?

**Comment by plutoless** [comment]
Token is useful only when you have turned your certificate switch on in ur agora dashboard

**Comment by plutoless** [comment]
it's not a mandatory parameter if you are still in early integration phase :) calculating token may need extra server setup

**Comment by gaganAriel** [comment]
please provide code for setup ringtone

**Comment by plutoless** [comment]
https://docs.agora.io/en/Interactive%20Broadcast/token?platform=All%20Platforms#using-a-token
you can start from here, but for initial integration to just make your demo work, i suggest you to keep it null for now

**Comment by gaganAriel** [comment]
please provide code for setup ringtone

**Comment by plutoless** [comment]
are you talking about phone ringtone? we don't control phone ringtone in our sdk

**Comment by gaganAriel** [comment]
ok thanks you can close this issue
