### ISSUE TITLE
I need to get the width and height of the video through the remote video track.

### ISSUE THREAD

**Issue by yeon1216** [AgoraIO/Basic-Video-Call#270]
**Describe the bug**
I need to get the width and height of the video through the remote video track.
I expected to know the length of video horizontal and vertical through the getStats() function of remote video track. However, I checked the values of the getStats() function in the log and found that they were all zero.
I referred to the AgoraIO/Basic-Video-Call/One-to-One-Video/Agora-Web-Tutorial-1to1-React-NG project.
[https://github.com/AgoraIO/Basic-Video-Call/tree/master/One-to-One-Video/Agora-Web-Tutorial-1to1-React-NG](url)

**Expected behavior**
I need to get the width and height of the video through the remote video track.

**Screenshots**
![image](https://user-images.githubusercontent.com/37677444/113528774-98a24280-95fc-11eb-900e-779c3bfc4b5f.png)

**Desktop (please complete the following information):**
 - OS: Mac OS X
 - Browser: Chrome
 - Version: 89

**My Code**
``` 
// Subscribe to a remote user
  rtc.client.on("user-published", async (user, mediaType) => {

    // Subscribe to a remote user
    await rtc.client.subscribe(user);
    console.log("subscribe success");

    if (mediaType === "video" || mediaType === "all") {
      // Get `RemoteVideoTrack` in the `user` object.
      const remoteVideoTrack = user.videoTrack;

      console.log('remoteVideoTrack',remoteVideoTrack)
      console.log('remoteVideoTrack.getStats()',remoteVideoTrack.getStats())
      console.log('remoteVideoTrack.getMediaStreamTrack()',remoteVideoTrack.getMediaStreamTrack())
      console.log('remoteVideoTrack.getUserId()',remoteVideoTrack.getUserId())
      console.log('remoteVideoTrack.getTrackId()',remoteVideoTrack.getTrackId())
      console.log('remoteVideoTrack.getStats().width',remoteVideoTrack.getStats().receiveResolutionWidth)
      console.log('remoteVideoTrack.getStats().height',remoteVideoTrack.getStats().receiveResolutionHeight)

      const remoteWidth = "320px"
      const remoteHeight = "240px"
      // Dynamically create a container in the form of a DIV element for playing the remote video track.
      const playerContainer = document.createElement("div");
      // Specify the ID of the DIV container. You can use the `uid` of the remote user.
      playerContainer.id = user.uid;
      console.log('playerContainer', playerContainer)
      playerContainer.style.width = remoteWidth;
      playerContainer.style.height = remoteHeight;
      if(playerContainer.id===broadcasterUid){
        playerContainer.style.border = "4px dashed #bcbcbc";
      }
      // document.body.append(playerContainer);

      const videoBox = e('.video-agora-box')
      videoBox.appendChild(playerContainer)

      // Play the remote audio and video tracks
      // Pass the ID of the DIV container and the SDK dynamically creates a player in the container for playing the remote video track
      remoteVideoTrack.play(playerContainer.id);
    }

    if (mediaType === "audio" || mediaType === "all") {
      // Get `RemoteAudioTrack` in the `user` object.
      const remoteAudioTrack = user.audioTrack;
      // Play the audio track. Do not need to pass any DOM element
      remoteAudioTrack.play();
    }
  });
```

**Comment by yoreland** [comment]
Did you check this API?
https://docs.agora.io/en/Interactive%20Broadcast/API%20Reference/web_ng/interfaces/iagorartcclient.html#getremotevideostats

**Comment by yeon1216** [comment]
I used getRemoteVideoStats(), but I still can't get the value I want.

![image](https://user-images.githubusercontent.com/37677444/122343891-27c6c180-cf81-11eb-94fe-4f12aca31d40.png)
![image](https://user-images.githubusercontent.com/37677444/122344031-4fb62500-cf81-11eb-8788-4f2a17eddbc4.png)

**Comment by gilamarko** [comment]
any answers on that?

**Comment by plutoless** [comment]
@gilamarko getRemoteVideoStats should be the right answer

**Comment by gilamarko** [comment]
indeed that's the answer, for some reason when using console.log(client.getRemoteVideoStats()), the attributes of height and width are 0. But later on they are initialized, maybe I should call the function  in another place

**Comment by plutoless** [comment]
you should set a timer and call this api periodically. the value may not be available at initial stage, and may change during the call session.

**Comment by gilamarko** [comment]
Correct, thx for the reply!
