### ISSUE TITLE
Help Required -- Remote video view is stretched when set to VideoCanvas.RENDER_MODE_FILL

### ISSUE THREAD

**Issue by hamza-maqsood** [AgoraIO/Basic-Video-Call#274]
I need to render the remote video view on a tablet screen, and it should take the full screen of it but the video becomes stretched and looks strange.
this is my code for it:
mRtcEngine!!.setupRemoteVideo(VideoCanvas(mRemoteView, VideoCanvas.RENDER_MODE_FILL, uid))

how to render it in a full screen video and still get a decent view?

**Comment by plutoless** [comment]
could you pls provide a screenshot?

**Comment by hamza-maqsood** [comment]
https://imgur.com/a/7MEJfZ8

**Comment by hamza-maqsood** [comment]
This photo is an old one, there's a little margin from the bottom but I tried full screen but the same results

**Comment by plutoless** [comment]
try using RENDER_MODE_HIDDEN for aspect fill

**Comment by hamza-maqsood** [comment]
tried the hidden mode as well, same results :(

**Comment by hamza-maqsood** [comment]
it's better now with RENDER_MODE_HIDDEN
thanks for the help
