### ISSUE TITLE
Cannot View Video or Hear Audio!

### ISSUE THREAD

**Issue by kaushal-gawri9899** [AgoraIO/Basic-Video-Call#276]
I am trying to test the sdk on my local server but while joining the meeting with multiple users, I am unable to see any video or hear any audio. Only the call termination button works but the rest do not. The same App Id and Token let me in using the following link so it shouldn't be an issue with the credentials :
https://webdemo.agora.io/agora-websdk-api-example-4.x/basicVideoCall/index.html

Please look into it and update as early as possible
![image](https://user-images.githubusercontent.com/34962753/117309601-327d3980-aea0-11eb-9155-08b4b1239dbc.png)

**Comment by yoreland** [comment]
Can you share your console logs on your local server?
Btw, webRTC don't work on plain http server, you may need enable https on your server

**Comment by kaushal-gawri9899** [comment]
These are the console logs throwing errors on isVideoOn and isAudioOn functions when i click on the camera and mic icon. 
![image](https://user-images.githubusercontent.com/34962753/117323519-9443a080-aeac-11eb-9c98-901740b14d62.png)

Regarding running my local server on https, I am still trying to add the ssl certificate. Can this be a reason why no video is displayed?

**Comment by yoreland** [comment]
just quick check locally and can't reproduce your issue:
<img width="486" alt="image" src="https://user-images.githubusercontent.com/8169775/117379892-15ca1b80-af0b-11eb-9a2e-a00a25538520.png">

Can you check in your case which Agora SDK version you are using, it is 2.9.0
