### ISSUE TITLE
110 token is invalid 

### ISSUE THREAD

**Issue by aakashpatel7979** [AgoraIO/Basic-Video-Call#282]
I'm getting "110 token is invalid" but when I created from agora console (agora temp token is working) and when I created from source code example of PHP.

-appID 
-appCertificate 
-channelName 
-uid 
===>I'm using 'Token with int uid: '

so I think I have issued from the android side "Join channel" so anyone who can help.

**Comment by yoreland** [comment]
From this information, seems the issue should be on PHP token generator side, did you try the same on https://webdemo.agora.io/agora-web-showcase/examples/Agora-Web-Tutorial-1to1-Web/
?

**Comment by aakashpatel7979** [comment]
yes it's working on this link

**Comment by aakashpatel7979** [comment]
> From this information, seems the issue should be on PHP token generator side, did you try the same on https://webdemo.agora.io/agora-web-showcase/examples/Agora-Web-Tutorial-1to1-Web/
> ?

i'm getting 107 (warning code) when two user connected with same user id and i'm using same uid because the token is generated via uid.
This webdemo is working with 
-appid
-channel name
-token
but  without uid so please help me how to connect video call with uid.
