### ISSUE TITLE
107 The server rejected the request to open the channel. The server cannot process this request or the request is illegal.

### ISSUE THREAD

**Issue by aakashpatel7979** [AgoraIO/Basic-Video-Call#283]

**Comment by aakashpatel7979** [comment]
i'm getting 107 (warning code) when two user connected with same user id and i'm using same uid because the token is generated via uid.
This webdemo is working with
-appid
-channel name
-token
but without uid so please help me how to connect video call with uid.

**Comment by yoreland** [comment]
If you are using temporary token generated on agora console, you could use the token across different uid. If the token generated yourselves, you need generate it relatively

**Comment by aakashpatel7979** [comment]
Yes Its working 
Thanks....
