### ISSUE TITLE
alert message should be displayed as "Paused" or "Reconnecting" if one user is offline

### ISSUE THREAD

**Issue by JanmejayIndium** [AgoraIO/Basic-Video-Call#291]
**Describe the bug**
If the internet is disconnected for one user then in another user mobile the video is stalled but no alert message is displayed as "Paused" or "Reconnecting"
**To Reproduce**
1.Initiate the call 
2..Disconnect the internet 
3.Observe the user with internet connection no message is display about the other user who is offline.

**Expected behavior**
alert message should be displayed as "Paused" or "Reconnecting"

**Desktop (please complete the following information):**
 - OS: Android 11
 - App

**Smartphone (please complete the following information):**
 - Device: Samsung A50
 - OS: 11
 App : https://github.com/AgoraIO/Basic-Video-Call/tree/master/Group-Video/OpenVideoCall-Android

**Comment by yoreland** [comment]
Thanks for information, we will check

**Comment by JanmejayIndium** [comment]
> Thanks for information, we will check
Hi
When a user goes offline we can check this by using method  onUserOffline(int uid, int reason).
Which method we can use to check he is back online?
