### ISSUE TITLE
Agora-SDK [DEBUG]: [FB79B] The time to join the channel is greater than 5 seconds

### ISSUE THREAD

**Issue by vatsaliml** [AgoraIO/Basic-Video-Call#341]
Agora-SDK [DEBUG]: [FB79B] The time to join the channel is greater than 5 seconds
i'm getting this error message

**i have used this code for generate RTC token:** 
$appId = "970CA35de60c44645bbae8a215061b33";
$appCertificate = "5CFd2fd1755d40ecb72977518be15d3b";
$channelName = "7d72365eb983485397e3e3f9d460bdda";
$uid = 2882341273;
$uidStr = "2882341273";
$tokenExpirationInSeconds = 3600;
$privilegeExpirationInSeconds = 3600;

$token = RtcTokenBuilder2::buildTokenWithUid($appId, $appCertificate, $channelName, $uid, RtcTokenBuilder2::ROLE_PUBLISHER, $tokenExpirationInSeconds, $privilegeExpirationInSeconds);
echo 'Token with int uid: ' . $token . PHP_EOL;

**after successful token generate when i'm trying to test token i'm facing this error message in console **
Agora-SDK [DEBUG]: [2C487] The time to join the channel is greater than 5 seconds

when i'm generate RTC token from agora Dashboard it's work perfectly, but when trying to generate token using above code it's  throw above error.   

please help me to solve problem.

**Comment by plutoless** [comment]
have you filled appId/appCertificate/channelName/uid with the values you need/have?

**Comment by vatsaliml** [comment]
@plutoless 
i have filled all the required parameters
**$appId = "970CA35de60c44645bbae8a215061b33";
$appCertificate = "5CFd2fd1755d40ecb72977518be15d3b";
$channelName = "7d72365eb983485397e3e3f9d460bdda";
$uid = 2882341273;
$uidStr = "2882341273";
$tokenExpirationInSeconds = 3600;
$privilegeExpirationInSeconds = 3600;**

here you can see all the details, i have filled.

**Comment by plutoless** [comment]
970CA35de60c44645bbae8a215061b33
this appid appears to be fake appid we put in our sample code. are you sure you have replaced these value with the ones you have?

**Comment by vatsaliml** [comment]
@plutoless 
yes i have replaced my own app-id and certificate Id.
and one thing i noticed that when **im passing 0 as uid is working fine** and **when passing any value instead of 0 is not working**

**Comment by plutoless** [comment]
if you pass random uid, you will need to ensure the uid you used to generate the token match with the uid you used to join the channel. otherwise your join will be rejected.

**Comment by vatsaliml** [comment]
okay it's fine to pass uid as 0 for now.
thanks for your support and help.
