### ISSUE TITLE
Flutter Example

### ISSUE THREAD

**Issue by sfaizanh** [AgoraIO/Basic-Video-Call#35]
Hi, Can you add **[Flutter](https://flutter.io)** Example for **[Basic-Video-Call](https://github.com/AgoraIO/Basic-Video-Call)** and **[Basic-Audio-Call](https://github.com/AgoraIO/Basic-Audio-Call)**

**Comment by plutoless** [comment]
hi @sfaizanh  https://github.com/AgoraIO-Community/Agora-Flutter-Quickstart this is equivalent to Basic-Video-Call for flutter
