### ISSUE TITLE
mac 本地首帧的size为什么总是960*720

### ISSUE THREAD

**Issue by wincax88** [AgoraIO/Basic-Video-Call#36]
设置了 320x240
- (void)setupVideo {
    [self.agoraKit enableVideo];
 
    AgoraVideoEncoderConfiguration *configuration =
        [[AgoraVideoEncoderConfiguration alloc] initWithSize:AgoraVideoDimension320x240
                                                   frameRate:AgoraVideoFrameRateFps15
                                                     bitrate:AgoraVideoBitrateStandard
                                             orientationMode:AgoraVideoOutputOrientationModeAdaptative];
    
    [self.agoraKit setVideoEncoderConfiguration:configuration];
}

但在 firstLocalVideoFrameWithSize 中的size一直是960*720
- (void)rtcEngine:(AgoraRtcEngineKit * _Nonnull)engine firstLocalVideoFrameWithSize:(CGSize)size elapsed:(NSInteger)elapsed {
    NSLog(@"size : %d, %d",  (int)size.width, (int)size.height);
}

**Comment by wincax88** [comment]
用 Agora-macOS-Tutorial-Objective-C-1to1 测试的

**Comment by dubian0608** [comment]
FaceTime camera的采集分辨率只有960*720

**Comment by wincax88** [comment]
> camera
thanks
