### ISSUE TITLE
群视频demo导入编译报错

### ISSUE THREAD

**Issue by haoyueyu** [AgoraIO/Basic-Video-Call#37]
D:\androidDemo\OpenVideoCall-Android\app\src\main\java\io\agora\openvcall\ui\MainActivity.java:182: 错误: 找不到符号
    public void onLastmileProbeResult(final IRtcEngineEventHandler.LastmileProbeResult result) {
                                                                  ^
  符号:   类 LastmileProbeResult
  位置: 类 IRtcEngineEventHandler
D:\androidDemo\OpenVideoCall-Android\app\src\main\java\io\agora\openvcall\model\WorkerThread.java:156: 错误: 找不到符号
            public void onLastmileProbeResult(LastmileProbeResult result) {
                                              ^
  符号: 类 LastmileProbeResult
D:\androidDemo\OpenVideoCall-Android\app\src\main\java\io\agora\openvcall\model\WorkerThread.java:155: 错误: 方法不会覆盖或实现超类型的方法
            @Override
            ^
D:\androidDemo\OpenVideoCall-Android\app\src\main\java\io\agora\openvcall\model\MyEngineEventHandler.java:129: 错误: 找不到符号
        public void onLastmileProbeResult(IRtcEngineEventHandler.LastmileProbeResult result){
                                                                ^
  符号:   类 LastmileProbeResult
  位置: 类 IRtcEngineEventHandler
D:\androidDemo\OpenVideoCall-Android\app\src\main\java\io\agora\openvcall\model\MyEngineEventHandler.java:128: 错误: 方法不会覆盖或实现超类型的方法
        @Override
        ^
D:\androidDemo\OpenVideoCall-Android\app\src\main\java\io\agora\openvcall\model\MyEngineEventHandler.java:223: 错误: 方法不会覆盖或实现超类型的方法
        @Override
        ^
D:\androidDemo\OpenVideoCall-Android\app\src\main\java\io\agora\openvcall\model\MyEngineEventHandler.java:225: 错误: 找不到符号
            super.onAudioMixingStateChanged(state, errorCode);
                 ^
  符号: 方法 onAudioMixingStateChanged(int,int)
D:\androidDemo\OpenVideoCall-Android\app\src\main\java\io\agora\openvcall\ui\ChatActivity.java:693: 错误: 找不到符号
                    rtcEngine().setRemoteUserPriority(uid, Constants.USER_PRIORITY_HIGH);
                                                                    ^
  符号:   变量 USER_PRIORITY_HIGH
  位置: 类 Constants
D:\androidDemo\OpenVideoCall-Android\app\src\main\java\io\agora\openvcall\ui\ChatActivity

**Comment by plutoless** [comment]
用的是最新的2.4 sdk吗？看起来是sdk版本不对导致部分符号没找到

**Comment by haoyueyu** [comment]
用的是2.3.3 sdk,谢谢

**Comment by haoyueyu** [comment]
用2.4.0sdk可以了，希望将github上边的说明修改一下，谢谢

**Comment by plutoless** [comment]
好 我们会尽快更新
