### ISSUE TITLE
Switch user screens

### ISSUE THREAD

**Issue by boboci9** [AgoraIO/Basic-Video-Call#41]
Hi,

I went through the documentation but I couldn't find anything about switching the screens, what I need to do is load the first user that joins the call in the big canvas and move the current user in a small box.
Can you help me in what direction to take?

Thanks, 
Bogi

**Comment by plutoless** [comment]
hi @boboci9 , which platform are you working on?

**Comment by boboci9** [comment]
Hi @plutoless, I am using the web platform from react. Sorry I didn't mention these details before. LEt me know if you need any other info.

**Comment by plutoless** [comment]
I think you just need to change the container css style?
