### ISSUE TITLE
Using switchDevice is causing DOMException 

### ISSUE THREAD

**Issue by mordka** [AgoraIO/Basic-Video-Call#43]
Agora Web SDK 2.6.1

After calling `stream.switchDevice()` I can see the following error thrown in Chrome dev console:

```
Unhandled Promise rejection: Failed to set remote answer sdp: Called in wrong state: kStable ; Zone: <root> ; Task: null ; Value: DOMException undefined
```

The key functionality works fine. 

For reference:
https://stackoverflow.com/questions/48963787/failed-to-set-local-answer-sdp-called-in-wrong-state-kstable

**Comment by plutoless** [comment]
@mordka thanks for the report. I will report this to SDK dev

**Comment by NarHakobyan** [comment]
any news?
