### ISSUE TITLE
Group-video call error on execute

### ISSUE THREAD

**Issue by dluisbrbr** [AgoraIO/Basic-Video-Call#46]
Group video call.
When running the sample, with npm run dev, the following errors are reported in the browser console:
14: 08: 10: 704 Now-SDK [ERROR]: [100CC] User join failed [ERR_DYNAMIC_USE_STATIC_KE]
4: 08: 10: 720 Now-SDK [ERROR]: [88812] User join failed [ERR_DYNAMIC_USE_STATIC_KE]
Uncaught (in promise) ERR_DYNAMIC_USE_STATIC_KE
My environment is:
Windows 7
Node 11.11.0
Npm: 6.9.0
The example does not trigger the camera or even the sound.
How should I correct the reported errors?

**Comment by plutoless** [comment]
hi @dluisbrbr , the error means you have enabled security certificate. in this case you will need a token to join the channel. if you do not yet have a token server deployed(which we have docs to explain), you may just go to your dashboard and generate a temp one for use.

**Comment by dluisbrbr** [comment]
Hi, Qianze.Thanks for the feedback.I generated the token on the console. 
How do I use it in the app?

Abs.

Dalton Luis
cel -55 11 94538-7987
Advos ateliê de informática. 

    Em quinta-feira, 6 de junho de 2019 14:14:46 BRT, Qianze Zhang <notifications@github.com> escreveu:  
 
 
hi @dluisbrbr , the error means you have enabled security certificate. in this case you will need a token to join the channel. if you do not yet have a token server deployed(which we have docs to explain), you may just go to your dashboard and generate a temp one for use.

**Comment by plutoless** [comment]
just put the token as the first parameter of your joinChannel function. Or if you are using websdk, it's join function
