### ISSUE TITLE
getting error : INVALID_VENDOR_KEY

### ISSUE THREAD

**Issue by darkworks** [AgoraIO/Basic-Video-Call#47]
i followed all steps when i click  JOIN button i get error 

`Agora-SDK [ERROR]: [9BA0E] Get server node failed [INVALID_VENDOR_KEY] https://ap-web-3.agora.io/api/v1 INVALID_VENDOR_KEY`

i copied and pasted correct app id from my dashboard project 

thanks

**Comment by plutoless** [comment]
Hi, if you have enabled certificate, you may need to provide a token when joining. The token can be generated directly from your dashboard project page. Calculate a new one and provide that as first parameter of join, see if it works for you.

**Comment by darkworks** [comment]
no i have not enabled certificates ,

**Comment by plutoless** [comment]
Are you using a new project? I believe for now a new project will automatically have certificate enabled

**Comment by plutoless** [comment]
or can you show me your code for joining media channel

**Comment by darkworks** [comment]
its fixed now  , was caused due to space it start of appid i copied from dashboard.

**Comment by GireshD** [comment]
Hi, I am facing issue  client join failed INVALID_VENDOR_KEY

**Comment by GireshD** [comment]
I am not using certificate, on dashboard no certificate enabled
