### ISSUE TITLE
how to generate unique video call links 

### ISSUE THREAD

**Issue by darkworks** [AgoraIO/Basic-Video-Call#51]
i have installed the video web call sample , to join call both parties should have to click on the join part and keep the channel value same . i wonder as it would be possible to generate direct video call link so that if user click on it the could start call with one another. 

Platform :   web platform ( php html js  )

**Comment by plutoless** [comment]
which platform are you talking about?

**Comment by darkworks** [comment]
web platform

**Comment by plutoless** [comment]
you can generate the link yourself. Put necessary info like channel & uid into url parameters. e.g. www.mycall.com/calls?channel=test&uid=3
So that when you open the page you can read the parameters from url and join directly.
To make your link more secure you can hash the link into a shorter one.

**Comment by darkworks** [comment]
thanks i will try that
