### ISSUE TITLE
Agora iOS Tutorial Objective-C demo运行后不出现画面

### ISSUE THREAD

**Issue by OmgKevin** [AgoraIO/Basic-Video-Call#53]
在参考readme的设置后运行至iOS10.3.1系统的真机上，黑色窗口不出现画面，其他功能按钮是正常的，请问是什么原因呢

**Comment by plutoless** [comment]
有错误吗？频道正常加入了吗？

**Comment by plutoless** [comment]
看一下errorDidOccur和didJoinChannel的回调有没有走到

**Comment by OmgKevin** [comment]
我这个跑的就是从官方地址下载下来的demo，代码层没做更改的，您可以跑一下试试看，应该是跟我看到的是一样的








在 2019-06-23 10:55:55，"Qianze Zhang" <notifications@github.com> 写道：


看一下errorDidOccur和didJoinChannel的回调有没有走到

**Comment by plutoless** [comment]
demo我们试过应该是没问题的，这边可能的一般就是给的appid和token不对，这边appid和token是怎么给的？

**Comment by OmgKevin** [comment]
你好谢谢已经解决不出现画面的问题，除了APPID 与临时token的问题，还涉及到在控制台的那个 频道名，也要跟代码里的channelId 唯一对应。请问，这个频道名后期在正式项目里我也要在控制台生成特定的频道名，然后在代码里唯一对应嘛，这个会不会是一个比较麻烦的点










在 2019-06-24 10:20:03，"Qianze Zhang" <notifications@github.com> 写道：


demo我们试过应该是没问题的，这边可能的一般就是给的appid和token不对，这边appid和token是怎么给的？

**Comment by plutoless** [comment]
生产环境下你需要自己部署token服务器的，控制台帮你生成只是帮你加速前期开发
