### ISSUE TITLE
Support: Webhook in Agora

### ISSUE THREAD

**Issue by NarHakobyan** [AgoraIO/Basic-Video-Call#55]
Hi folks, currently I am looking for webhooks of the video call, I tried to do research but unfortunately can't find any info related to webhook.
How can I get a duration of video call after the end? for example, user can turn off PC and need a webhook to trigger me a duration of a call

**Comment by plutoless** [comment]
sry for late reply. can you contact our sales? we have a backend notification service but that's not for public use

**Comment by NarHakobyan** [comment]
I sent an email but they are not repliyed

**Comment by plutoless** [comment]
https://docs.agora.io/en/Agora%20Platform/community?_ga=2.268560625.1887031822.1573724841-2140392182.1568170006
sorry in case still interested, you may find following ways to reach our community for potential talk.
