### ISSUE TITLE
error: cannot find symbol variable receivedFrameRate in CallActivity.java of OpenVideoCall-Android/Group-Video/Basic-Video-Call

### ISSUE THREAD

**Issue by wann2** [AgoraIO/Basic-Video-Call#57]
Basic-Video-Call/Group-Video/OpenVideoCall-Android/

CallActivity.java > compile error happens in 661 line.

mGridVideoViewContainer.addVideoInfo(stats.uid, new VideoInfoData(stats.width, stats.height, stats.delay, stats.receivedFrameRate, stats.receivedBitrate));

stats.receivedFrameRate
error: cannot find symbol variable receivedFrameRate

**Comment by plutoless** [comment]
fixed.
