### ISSUE TITLE
Build command failed.

### ISSUE THREAD

**Issue by mt131** [AgoraIO/Basic-Video-Call#58]
/Basic-Video-Call-master/Group-Video/OpenVideoCall-Android/app/src/main/cpp/video_preprocessing_plugin_jni.cpp:5:10: fatal error: 'agora/IAgoraRtcEngine.h' file not found

**Comment by plutoless** [comment]
@mt131  please copy the header files under libs/include folder from your downloaded sdk into /Basic-Video-Call-master/Group-Video/OpenVideoCall-Android/app/src/main/cpp/agora.
sorry for not making this clear, i will update the readme shortly
