### ISSUE TITLE
Agora-Web-Tutorial-1to1 运行时报错

### ISSUE THREAD

**Issue by secondmax** [AgoraIO/Basic-Video-Call#59]
项目运行起来之后无法加入直播，报错信息：ERR_STATIC_USE_DYANMIC_KE
![image](https://user-images.githubusercontent.com/6166338/61118080-91eba780-a4ca-11e9-9593-d41aa926c2ae.png)
文档上有说是静态厂商使用了动态 Key，但是怎么生成静态Key?

**Comment by plutoless** [comment]
你加入频道的时候第一个参数填的什么？

**Comment by secondmax** [comment]
> 你加入频道的时候第一个参数填的什么？

在dashboard中生成的temp token
