### ISSUE TITLE
Where do we get the access token?

### ISSUE THREAD

**Issue by mgtheboss-1** [AgoraIO/Basic-Video-Call#64]
Hi,

We are following the steps mentioned here, https://github.com/AgoraIO/Basic-Video-Call/blob/master/One-to-One-Video/Agora-Web-Tutorial-1to1/README.md . We are unable to find the section on agora io dashboard where we can generate an access token. Please guide us in the right direction. We appreciate your cooperation.

**Comment by plutoless** [comment]
![image](https://user-images.githubusercontent.com/471561/61765214-b91d6f80-ae0e-11e9-9b77-bac216f8a959.png)
sorry my dashboard is in chinese. you can see similar UI in your dashboard, and under project details you shall find a key icon button which helps you to generate a temp access token.

**Comment by mgtheboss-1** [comment]
In my case, the key is missing.
![key-missing-e](https://user-images.githubusercontent.com/47972017/61768064-e153a100-ae03-11e9-8bf0-9999962d6037.jpg)

**Comment by plutoless** [comment]
@mgtheboss-1  it means you have not yet enabled certificate. In this case, you do not need a token to join channel
