### ISSUE TITLE
how to connet Live Broadcast one mobile to another mobile live view 

### ISSUE THREAD

**Issue by Lalitchaudhary2** [AgoraIO/Basic-Video-Call#82]

**Comment by plutoless** [comment]
simply use the same appid and join the same channel

**Comment by Lalitchaudhary2** [comment]
I have downloaded your agora live broadcast video sdk.
I have see Demo(Open-Live-Android) and run apk after launch app then show input name of the live what value i pass in this text filed.

**Comment by plutoless** [comment]
that's exactly the channel name, you may have two phones starting the same app and enter the same channel. then you shall be able to see each other

**Comment by Lalitchaudhary2** [comment]
thank you
