### ISSUE TITLE
web screen sharing chrome extension does not work!

### ISSUE THREAD

**Issue by echoYZ1208** [AgoraIO/Basic-Video-Call#86]
After install the web screen chrome extension and config the extensionID, there's still an error: "No response from Chrome Plugin. Plugin not installed properly".

**Comment by plutoless** [comment]
which plugin have you installed?

**Comment by echoYZ1208** [comment]
Agora Web Screensharing 0.0.0.1
https://chrome.google.com/webstore/detail/agora-web-screensharing/minllpmhdgpndnkomcoccfekfegnlikg

**Comment by plutoless** [comment]
this plugin only works with websites deployed to agora host. You will need your own plugin to work with your own websites, for how, take a look at https://docs.agora.io/en/Video/chrome_screensharing_plugin

**Comment by echoYZ1208** [comment]
I run it at localhost but it does't work，and there‘s also statement in this doc.
"3. Change the domain name
Open the manifest.json file in the extension package, and change the domain name in the line beginning with matches.
If you run the extension on localhost, you do not need to set matches."

**Comment by plutoless** [comment]
you can't use our extension, even if you run it on localhost.
you need to download the plugin, edit the content to suit your own needs and load it with developer mode (or publish it to google store when going production).

**Comment by echoYZ1208** [comment]
Yeah. I got it! The English doc is very very different from the Chinese docs and there's no statement about "Uploading the Google Chrome Screen-sharing Extension".

**Comment by echoYZ1208** [comment]
Anyway Thank you！

**Comment by wangjie-agora** [comment]
> Yeah. I got it! The English doc is very very different from the Chinese docs and there's no statement about "Uploading the Google Chrome Screen-sharing Extension".

Thanks for your comment. The Chinese version does not include the uploading section because most people can’t access Chrome web store in China. We’ll try to keep the CN and EN docs in sync where possible. If you find other doc issues, please let us know. Your feedback is much appreciated.

**Comment by echoYZ1208** [comment]
按照文档，我删除了manifest中的key字段，安装扩展，修改填入新的extensionId，在localhost上运行，但还是出现一样的错误。我必须上传到chrome商店吗？

**Comment by dongsettle** [comment]
在localhost上运行插件版本的屏幕共享之前，需要做的操作如下：
1、manifest.json配置文件中matches参数加上："*://localhost/*"，并且不要删除这里面的key字段；
2、打开开发者模式，在chrome上加载本地的这个扩展程序；
然后就可以去尝试创建屏幕共享流了。（chrome72之后就支持无插件版本的屏幕共享，不需要安装插件对于用户来说方便很多，如果可以的话建议直接使用无插件的屏幕共享方式）
