### ISSUE TITLE
Switching between audio/ video call

### ISSUE THREAD

**Issue by varunrathi28** [AgoraIO/Basic-Video-Call#89]
Hi,
I am using AgoraSdk for video call. We want to implement a feature to enable user switching between audio to video call and vice versa. But there is no documentation regarding that. Please help

**Comment by plutoless** [comment]
you can mute/unmute via api calls, in case this is what you need.

**Comment by varunrathi28** [comment]
If we move from Video to audio call, does the bandwidth gets managed automatically? Since video call would be taking more bandwidth than audio call.

**Comment by plutoless** [comment]
@varunrathi28 yes it gets managed automatically.

**Comment by varunrathi28** [comment]
Thanks @plutoless . You were very helpful.
